Qualify images to avoid incompatibility with CRI-O
rancher/rancher pull request #27755
Opened 2020-06-26 21:28 UTC by kubealex

cri-o doesn't support unqualified images by default.
This fixes the behaviour, solving https://github.com/rancher/rancher/issues/27754

2020-06-30 21:54 UTC, kubealex commented
bump

2020-07-20 23:10 UTC, kubealex commented
@jiaqiluo @aiyengar2

2020-08-04 03:06 UTC, michaelandrepearce commented
This would break air gap installs with private registries?

2020-12-28 23:37 UTC, kubealex commented
bump @aiyengar2

2021-01-04 22:33 UTC, aiyengar2 requested changes
@kubealex this PR still needs changes as described in https://github.com/rancher/rancher/pull/27755#pullrequestreview-461021609 to avoid breaking in air-gapped environments

2022-06-09 02:14 UTC, closed without merging