Validation - Add proxy setup
rancher/rancher pull request #29455
Opened 2020-10-09 16:30 UTC by bmdepesa

* Creates a proxy server
* Creates a Rancher semi-airgapped configured to use the proxy (no public IP)
* Allows to create nodes for a custom cluster which are configured to use the proxy

2020-10-09 22:13 UTC, jiaqiluo requested changes

2020-10-09 22:13 UTC, jiaqiluo commented on tests/validation/tests/v3_api/test_proxy.py
> +def add_cluster_to_rancher(bastion_node, ag_nodes):
add nodes to cluster?

2020-11-03 22:08 UTC, jiaqiluo approved these changes
LGTM

2020-11-04 21:36 UTC, sowmyav27 approved these changes
LGTM. Jenkins works

2020-11-04 21:37 UTC, merged