Add rke2 airgap deployment methods
rancher/rancher pull request #29515
Opened 2020-10-14 16:55 UTC by rancher-max

This provides options for additional server arguments which will become necessary when code is added to add these clusters to Rancher. More is required for this enhancement, so this will come in a future PR.

Currently there are two ways to deploy RKE2 in an airgap environment: 
  - Through a private registry that is NOT password protected but does require TLS
  - Tarball method

See rke2 docs for more info on these. This just automates the process for us for easier testing. For tarball method, a bastion server is required to already be present and user must supply the ID. For private registry method, it will create the bastion server itself.

2020-10-26 16:37 UTC, ShylajaDevadiga commented on tests/validation/tests/v3_api/test_airgap.py
> +        node_cmd = "{} get nodes --kubeconfig {}".format(kubectl, kubeconfig)
Can we skip passing kubectl as param?

2020-10-26 16:44 UTC, ShylajaDevadiga commented on tests/validation/tests/v3_api/test_airgap.py
> +        node_cmd = "{} get nodes --kubeconfig {}".format(kubectl, kubeconfig)
pls ignore

2020-10-26 16:45 UTC, ShylajaDevadiga commented
LGTM

2020-10-29 20:57 UTC, bmdepesa requested changes
Can we move the RKE2 airgap tests to their own file?

2021-01-28 17:24 UTC, bmdepesa approved these changes

2021-01-28 18:17 UTC, jiaqiluo approved these changes
LGTM

2021-01-28 18:31 UTC, merged