updated kontainer engine
rancher/rancher pull request #29586
Opened 2020-10-16 22:02 UTC by paynejacob

2020-10-16 23:28 UTC, rmweir requested changes
Have to vendor changes in v2.4.

2020-10-16 23:34 UTC, rmweir approved these changes
LGTM

2020-10-17 10:36 UTC, superseb approved these changes

2020-10-19 16:13 UTC, merged

2020-10-19 18:24 UTC, paynejacob commented
https://github.com/rancher/rancher/issues/28317