Update system charts to release-v2.5 branch
rancher/rancher pull request #29842
Opened 2020-10-29 19:35 UTC by mrajashree

2020-10-29 20:01 UTC, cbron requested changes

2020-10-29 20:01 UTC, cbron commented on package/Dockerfile
> +ARG SYSTEM_CHART_DEFAULT_BRANCH=release-v2.5
One more https://github.com/rancher/rancher/blob/release/v2.4/scripts/package#L7

2020-10-29 20:14 UTC, cbron approved these changes

2020-10-30 20:40 UTC, mrajashree commented
Closing in favor of https://github.com/rancher/rancher/pull/29869/files

2020-10-30 20:40 UTC, closed without merging