Create and upgrade multiple k3s clusters with validation tests
rancher/rancher pull request #30169
Opened 2020-11-20 16:46 UTC by rancher-max

- Adds Jenkins job to import multiple k3s clusters, run preupgrade, upgrade, and run postupgrade jobs
- Adds upgrade_cluster code for k3s clusters
- Removes some extraneous prints and "multinode" text from k3s creation code

2021-01-13 18:17 UTC, ShylajaDevadiga commented on tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_k3s_upgrade
> +                (env.CATTLE_TEST_URL == "" && env.ADMIN_TOKEN == "" && env.USER_TOKEN == "")) {
Can we simply this condition? Maybe using trim

2021-01-13 18:22 UTC, ShylajaDevadiga commented on tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_k3s_upgrade
> +                  RANCHER_CREATE_RESOURCES_PREFIX = "mystep1"
Upgrade variables are not used in deploy cluster.

2021-01-13 21:56 UTC, ShylajaDevadiga commented on tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_k3s_upgrade
> +                  RANCHER_CREATE_RESOURCES_PREFIX = "mystep2"
Is it possible to reuse the above code as it is just the PREFIX change?

2021-01-15 01:40 UTC, ShylajaDevadiga submitted a review, later dismissed
LGTM

2021-01-20 23:35 UTC, sowmyav27 requested changes

2021-01-20 23:54 UTC, rancher-max commented on tests/validation/tests/v3_api/test_custom_host_reg.py
> +    if UPDATE_KDM is True:
I put it before now! Thank you!

2021-01-21 05:22 UTC, sowmyav27 approved these changes
LGTM

2021-01-21 15:11 UTC, bmdepesa approved these changes
LGTM

2021-01-22 02:07 UTC, merged