Add LKE as a cluster driver
rancher/rancher pull request #30668
Opened 2021-01-04 19:17 UTC by phillc

2021-01-04 23:02 UTC, dramich commented on pkg/data/management/kontainerdriver_data.go
> +		"",
It looks like the UI is doing calls directly to the API, these should be proxied through rancher and a host would need to be added here.

2021-01-04 23:02 UTC, dramich requested changes
The build is failing due to a test needing to be updated. See https://github.com/rancher/rancher/commit/e57d0aef40b82304a8a7af9e39af6c11b235d8b2 as for what to update.

2021-01-06 15:01 UTC, phillc commented
I've fixed the api requests to go through the proxy. Luckily was able to piggyback the work from the node driver https://github.com/rancher/ui/blob/master/lib/shared/addon/linode/service.js

I haven't made the release for the component.js yet, as my manual testing passes on Rancher 2.4.11, but not master-head due to `Cluster health check failed: cluster agent is not ready` so I need to dig a little deeper.

2021-01-06 15:46 UTC, dramich commented
@phillc Sounds good, just ping me when you are ready.

2021-01-13 17:57 UTC, dramich approved these changes

2021-01-13 17:57 UTC, merged