[2.5] switch to upstream saml library
rancher/rancher pull request #30858
Opened 2021-01-15 00:03 UTC by paynejacob

#30291 

PROBLEM:

Rancher was maintaining a fork of crewjam/saml to fix a since resolved issue.  This has put us behind the latest version of the upstream library.  Now that the original issue is resolved we can switch back to the upstream.

SOLUTION:

Switched back to the upstream library in `go.mod`.  In the latest version of crewjam/saml the generic cookie database interface was remove in favor of a more concise approach for storing data. [link](https://github.com/crewjam/saml/commit/695c7b1abe5223dd32db3fa60915b58116880b29) Rancher depended on this generic interface to store some extra rancher specific data. I pulled the removed code into the rancher saml package.

TESTING:
I tested this with a keycloak setup and was able to configure keycloak and log in as a keycloak user.

2021-01-15 16:53 UTC, superseb requested changes
Build failure

2021-01-16 09:00 UTC, superseb approved these changes

2021-01-20 15:43 UTC, paynejacob commented
#30306

2021-01-30 09:12 UTC, superseb approved these changes

2021-02-02 00:28 UTC, luthermonson approved these changes

2021-02-02 00:51 UTC, merged