Added etcd snapshot timeout parameter
rancher/rancher pull request #30951
Opened 2021-01-22 15:22 UTC by rawmind0

Issue https://github.com/rancher/rancher/issues/30663

2021-01-22 17:09 UTC, superseb requested changes
`91aed199f04c` comes from RKE `master`, `39c1e093d6f9` comes from RKE `release/v1.2`

2021-01-22 18:21 UTC, rawmind0 commented
@superseb , created required PR rancher/rke#2429 at rke master, and updated this PR to use it

2021-01-25 12:36 UTC, rawmind0 commented
Merged rancher/rke#2429, updated PR with proper go mod and generate

2021-01-26 08:27 UTC, superseb approved these changes

2021-01-27 16:57 UTC, merged