[v2.5] pass env vars to agent template
rancher/rancher pull request #31024
Opened 2021-01-28 01:54 UTC by kinarashah

https://github.com/rancher/rancher/issues/25412

2021-02-02 15:08 UTC, paynejacob approved these changes

2021-02-02 17:03 UTC, superseb requested changes
This includes the commit `Fix k3s upgrade dev image export` ?

2021-02-02 17:06 UTC, kinarashah commented
@superseb fixed it, was a new commit so had to rebase again

2021-02-02 17:07 UTC, superseb approved these changes

2021-02-03 18:45 UTC, paynejacob approved these changes

2021-02-03 18:53 UTC, merged