refactor k3s to support swappable components
rancher/rancher pull request #31030
Opened 2021-01-28 16:23 UTC by ShylajaDevadiga

2021-02-03 23:17 UTC, bmdepesa requested changes
Small typo in `RANCHER_CLUSTER_TYPE` default value, then LGTM

2021-02-03 23:17 UTC, bmdepesa commented on tests/validation/tests/v3_api/test_import_k3s_cluster.py
> +RANCHER_CLUSTER_TYPE = os.environ.get("RANCHER_CLUSTER_TYPE", "enternal_db")
Typo? `enternal_db`

2021-02-03 23:22 UTC, ShylajaDevadiga commented on tests/validation/tests/v3_api/test_import_k3s_cluster.py
> +RANCHER_CLUSTER_TYPE = os.environ.get("RANCHER_CLUSTER_TYPE", "enternal_db")
thanks. fixed

2021-02-08 16:20 UTC, rancher-max requested changes
Since we are using `.../terraform/k3s/...` now, can we remove the old files: `.../terraform/master/...` and `.../terraform/worker/...`?

2021-02-08 17:36 UTC, rancher-max approved these changes
LGTM

2021-02-08 17:48 UTC, bmdepesa approved these changes
LGTM

2021-02-08 17:48 UTC, merged