Pipeline Automation: create, run, delete
rancher/rancher pull request #31596
Opened 2021-03-04 20:26 UTC by slickwarren

ran flake8, added environment variables

added clarifying comments

moved test def to top of definitions, added delete test case
moved test to correct place, moved pipeline delete to main test

2021-03-08 18:02 UTC, izaac requested changes
Looks good besides a couple comments.

2021-03-08 18:05 UTC, bmdepesa commented on tests/validation/tests/v3_api/test_pipeline.py
> +    assert len(pipeline_details["p_client"].list_pipeline(
We want the delete to be explicitly called as part of the actual test here, not in the finalizer.

2021-03-08 18:10 UTC, izaac commented on tests/validation/tests/v3_api/test_pipeline.py
> +    assert len(pipeline_details["p_client"].list_pipeline(
Shouldn't we then have separate tests for Create and Delete?

2021-03-08 18:12 UTC, bmdepesa commented on tests/validation/tests/v3_api/test_pipeline.py
> +    assert len(pipeline_details["p_client"].list_pipeline(
The only difference then between the two cases would be the removal of the log assertion in the `delete` case, which seems redundant.

2021-03-08 18:16 UTC, izaac commented on tests/validation/tests/v3_api/test_pipeline.py
> +    assert len(pipeline_details["p_client"].list_pipeline(
We followed that pattern on backups that's why I brought it up here.
https://github.com/rancher/rancher/blob/master/tests/validation/tests/v3_api/test_bkp_restore_local.py

2021-03-09 00:47 UTC, slickwarren commented
closing in favor of #31633

2021-03-09 16:37 UTC, slickwarren commented on tests/validation/tests/v3_api/test_pipeline.py
> +    assert len(pipeline_details["p_client"].list_pipeline(
Is this resolved, or do I need to update something, @izaac

2021-03-09 17:55 UTC, izaac commented on tests/validation/tests/v3_api/test_pipeline.py
> +    assert len(pipeline_details["p_client"].list_pipeline(
keep it as-is for now, we can revisit later @slickwarren

2021-03-09 17:55 UTC, izaac approved these changes

2021-03-11 15:57 UTC, sowmyav27 approved these changes
LGTM

2021-03-11 17:34 UTC, bmdepesa approved these changes
LGTM

2021-03-11 17:35 UTC, merged