Fix GKE integration with clusterupstreamrefresher
rancher/rancher pull request #31936
Opened 2021-04-06 13:45 UTC by mjura

2021-04-06 14:29 UTC, cmurphy submitted a review, later dismissed
Thanks for catching this

2021-04-06 15:55 UTC, thedadams submitted a review, later dismissed

2021-04-06 19:03 UTC, rmweir requested changes

2021-04-06 19:03 UTC, rmweir commented on pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
> +	if providerRefreshInterval == "" {
I think this is an unnecessary indent.

2021-04-06 20:05 UTC, thedadams submitted a review, later dismissed

2021-04-06 20:15 UTC, rmweir reviewed
lint issues, otherwise LGTM

2021-04-07 07:51 UTC, mjura commented on pkg/controllers/management/clusterupstreamrefresher/cluster_upstream_refresher.go
> +	if providerRefreshInterval == "" {
sorry, I used `go fmt` again

2021-04-07 20:11 UTC, thedadams approved these changes

2021-04-07 20:32 UTC, rmweir approved these changes
LGTM

2021-04-07 23:48 UTC, cbron approved these changes
Lgtm. Only weirdness may be if provider isn't getting used correctly but it should be fine.

2021-04-07 23:48 UTC, merged

2021-04-07 23:51 UTC, cbron commented
backfix for: https://github.com/rancher/rancher/issues/31011