[Automation] - adding v2 chart install test
rancher/rancher pull request #32921
Opened 2021-05-27 21:37 UTC by izaac

This requires a Rancher and a Downstream cluster with enough resources.

Charts installed: 

- Monitoring v2
- Istio v2
- CIS Benchmark
- Logging

New Required Environment Variables (with sample values):

```
RANCHER_MONITORING_V2_VERSION=14.5.100
RANCHER_LOGGING_V2_VERSION=3.9.400
RANCHER_KIALI_V2_VERSION=1.32.100
RANCHER_ISTIO_V2_VERSION=1.9.500
RANCHER_CIS_V2_VERSION=1.0.400
TERRAFORM_VERSION=0.12.31 # optional but this has to be this version or newer
RANCHER_REMOVE_V2_CHARTS=False # Optional
```

Existing required Env vars.
```
CATTLE_TEST_URL
ADMIN_TOKEN
USER_TOKEN
RANCHER_CLUSTER_NAME
```

2021-06-01 21:47 UTC, bmdepesa requested changes

2021-06-01 21:47 UTC, bmdepesa commented on tests/validation/tests/v3_api/test_charts_v2.py
> +    for wl in charts_p_client.list_workload().data:
Can we check that some workloads exist as well?

2021-06-02 00:55 UTC, izaac commented
This will now use the latest version retrieved from the repo using the v1 api.

2021-06-03 17:37 UTC, bmdepesa approved these changes
LGTM

2021-11-02 16:27 UTC, izaac commented
This will be closed in favor of the new framework implementation for V2 charts.
There's a V1 charts effort followed up separately.

2021-11-02 16:27 UTC, closed without merging