Delete fleet-crd chart in post delete hook
rancher/rancher pull request #34344
Opened 2021-08-19 22:05 UTC by nickgerace

This _does_ contain copied code, but in order for the UX to be parseable, this PR deletes remaining Fleet resources (in this case, just the Fleet CRD chart) after all other Rancher resources are deleted.

Relevant issue: https://github.com/rancher/rancher/issues/34330

2021-08-19 22:07 UTC, nickgerace commented
To reviewers: I would be open to transforming the delete logic in a function, but I did not think we needed to. Willing to accept an alternative solution, keeping this in mind: https://github.com/rancher/rancher/pull/34344#issue-975085791

2021-08-20 00:12 UTC, jiaqiluo commented
Currently, the script will traverse the following list of namespaces to delete non-crd apps:
https://github.com/rancher/rancher/blob/50c33b29b096ff97048d323daf9fdbda1634f332/chart/values.yaml#L147-L150

A simpler way to achieve the same goal is to NOT skip if the app is  `fleet-crd` 
https://github.com/rancher/rancher/blob/50c33b29b096ff97048d323daf9fdbda1634f332/chart/scripts/post-delete-hook.sh#L35-L37

2021-08-20 14:43 UTC, nickgerace commented
> A simpler way to achieve the same goal as your current fix is to NOT skip if the app is fleet-crd
@jiaqiluo my approach was intentional: https://github.com/rancher/rancher/pull/34344#issue-975085791

However, I'd be willing to take the simple approach as well. I just dont want the user to be surprised when they see a single CRD chart get deleted. Perhaps one `echo "--- Exception: CRD chart to be deleted:" could suffice though. What are your thoughts?

2021-08-23 18:18 UTC, nickgerace commented
@jiaqiluo tried to minimize this, but realized that the other uninstall function contained a `continue` statement. I think repeating ourselves is fine given the UX context of not wanting to delete a single CRD chart in the middle of skipping all of them.

2021-08-23 18:27 UTC, jiaqiluo requested changes

2021-08-23 18:27 UTC, jiaqiluo commented on chart/scripts/post-delete-hook.sh
> +    if [[ "${app}" = "fleet-crd" ]] && [[ ! $(helm uninstall "${app}" -n "${namespace}") ]]; then
```suggestion
    if [[ "${app}" == "fleet-crd" ]] && [[ ! $(helm uninstall "${app}" -n "${namespace}") ]]; then
```

2021-08-23 18:28 UTC, StrongMonkey approved these changes

2021-08-23 19:13 UTC, nickgerace commented
Closing due to https://github.com/rancher/rancher/issues/34330#issuecomment-904040291

2021-08-23 19:13 UTC, closed without merging