Added server-version to list of settings to sync
rancher/rancher pull request #34846
Opened 2021-09-21 21:01 UTC by jakefhyde

From v2.6.0 onwards, the `server-version` setting has not been propagated to downstream clusters. Per https://github.com/rancher/rancher/issues/34479, pre 2.6 charts need to have the `rancher-version` annotation set to prevent installation on 2.6 clusters. This annotation works on upstream clusters, but because the `server-version` setting is not synced, downstream clusters will use the default which is `dev`, allowing all charts to be installed.

2021-09-21 21:42 UTC, StrongMonkey commented
@rmweir I think this will have a problem in hosted rancher if we copied the setting. The downstream cluster will have the same rancher version because we copied the setting. Ideally we should pass down the setting to an environment variable in cluster-agent . cc @ibuildthecloud  I think we should stop doing this handler and expose everything through cluster-agent....

2021-09-21 23:57 UTC, rmweir requested changes
@StrongMonkey makes a good point. This will need to be discussed before we move forward.

2021-09-21 23:59 UTC, rmweir commented
Maybe we could set the default based on upstream value?

2021-09-22 20:54 UTC, StrongMonkey commented
We need to stop syncing the setting from upstream to downstream. Instead we should pass down the server version to an environment variable into cluster-agent. Then controller should try to read the environment variable first, and if it is not set it should fallback to settings. There is a similar PR for system-default-registry https://github.com/rancher/rancher/pull/31902/files

2021-09-23 20:48 UTC, rmweir approved these changes
LGTM

2021-09-23 20:50 UTC, StrongMonkey approved these changes

2021-09-23 20:50 UTC, rmweir commented
Should be noted that this would cause the the value to become an env var on the downstream even if it wasn't set via env var for the upstream, which is unlikely to be overwritten unless someone using the downstream changed or removed the envar on the downstream host. I think @jakefhyde and I concluded that this is probably fine for server version.

2021-09-23 21:05 UTC, cbron approved these changes

2021-09-24 19:11 UTC, cbron commented
Holding off on merging this until we figure out https://github.com/rancher/dashboard/issues/4276

2021-09-28 15:57 UTC, merged