Limit norman API use of downstream cluster caches
rancher/rancher pull request #35510
Opened 2021-11-15 18:35 UTC by ibuildthecloud

The norman API layer should no use any caches from the down stream cluster.  This causes scaling issues.

2021-11-19 14:44 UTC, ibuildthecloud commented
Some context.  The vast major of calls to cluster.Manager.UserContext were in fact just trying to get a client to the downstream cluster and not access to the caches.  Ideally we want the Norman API to never access caches from downstream.  Fundamentally this isn't possible because of RBAC, but we will minimize the usage elsewhere.  A new method UserContextNoController to clearly indicate that the caller does not need access to caches.

Any place where Norman API was using a cache (that isn't RBAC) was modified to make live API calls.

2021-11-19 22:20 UTC, rmweir requested changes

2021-11-20 00:53 UTC, ibuildthecloud commented on pkg/api/norman/store/apiservice/filter.go
> +	lister, err := s.getAPIServiceClient(clustername)
Renamed

2021-11-20 01:00 UTC, rmweir approved these changes
LGTM

2021-11-20 04:23 UTC, merged