Defer start of pspdelete user controller
rancher/rancher pull request #35526
Opened 2021-11-16 17:27 UTC by ibuildthecloud

Only start pspdelete user controller if DefaultPodSecurityPolicyTemplateName is set on the v3.Cluster and its RKE2 managed cluster.  The pspdelete controller is used specifically for RKE2 to PSP with "psp.rke2.io/global-unrestricted" and "psp.rke2.io/global-restricted" annotations that are created by default for RKE2.

2021-11-18 00:28 UTC, rmweir requested changes

2021-11-18 00:28 UTC, rmweir commented on pkg/controllers/managementuser/pspdelete/pspdelete.go
> +		}
empty block here, guessing you meant to return

2021-11-18 00:28 UTC, rmweir commented on pkg/controllers/managementuser/pspdelete/pspdelete.go
> +		clusters, err := clusterCache.GetByIndex(cluster.ByCluster, userContext.ClusterName)
why use indexer instead of just getting it off the cache regularly?

2021-11-18 00:33 UTC, rmweir commented on pkg/controllers/managementuser/pspdelete/pspdelete.go
> +		clusters, err := clusterCache.GetByIndex(cluster.ByCluster, userContext.ClusterName)
Answer offline, resolved.

2021-11-18 18:51 UTC, rmweir submitted a review, later dismissed
one nit, then LGTM

2021-11-18 18:51 UTC, rmweir commented on pkg/controllers/managementuser/pspdelete/pspdelete.go
> +		if clusterSpec.DefaultPodSecurityPolicyTemplateName != "" && clusters[0].Spec.RKEConfig != nil {
nit:
```suggestion
		if clusterSpec.DefaultPodSecurityPolicyTemplateName != "" && clustersSpec.RKEConfig != nil {
```

2021-11-19 05:56 UTC, deniseschannon approved these changes

2021-11-19 06:03 UTC, deniseschannon approved these changes

2021-11-19 14:26 UTC, merged