Split nsserviceaccount handler between user and agent
rancher/rancher pull request #35557
Opened 2021-11-17 05:44 UTC by ibuildthecloud

The nsserviceaccount controllers is responsible for setting AutomountServiceAccountToken=false on the default service account in system namespaces (excluding kube-system and default).

2021-11-18 23:41 UTC, rmweir requested changes
I understand if we want to preserve it for metrics or to make it clear it's nearly the same as prior implementation but I think we might want to consider renaming the handlers since they aren't ServiceAccount handlers anymore.

2021-11-18 23:41 UTC, rmweir commented on pkg/controllers/managementagent/nsserviceaccount/nssvcaccnt.go
> +	clusterName           string
Doesn't look like these are used, remove if so.

2021-11-19 06:49 UTC, deniseschannon approved these changes

2021-11-19 14:27 UTC, ibuildthecloud commented on pkg/controllers/managementagent/nsserviceaccount/nssvcaccnt.go
> +	clusterName           string
removed

2021-11-19 21:35 UTC, rmweir approved these changes
LGTM. Discussed offline, name is fine.

2021-11-19 21:38 UTC, merged