Migrate Namespaces Assigned conditions from project to cluster
rancher/rancher pull request #35568
Opened 2021-11-17 17:00 UTC by jakefhyde

Description
-
Moved `DefaultNamespacesAssigned` and `SystemNamespacesAssigned` Conditions from cluster objects to associated default and system projects. During an upgrade, the project object may never have been updated (save for project sync), and having the cluster's status depend on the project being updated was causing issues due to the migrations having the wrangler controllers, but the project lifecycle having norman controllers. 

Info
-
Tested on HA  setup a number of times, confirmed issue was not reproducible.
Related Issue: https://github.com/rancher/rancher/issues/35411

2021-11-17 18:34 UTC, paynejacob requested changes

2021-11-17 18:34 UTC, paynejacob commented on pkg/rancher/migrations.go
> +	applyProjectConditionForNamespaceAssignment := func(label string, condition condition.Cond) error {
can we define this as a regular function and just pass in projectClient

2021-11-17 21:35 UTC, paynejacob approved these changes

2021-11-18 15:36 UTC, thedadams approved these changes

2021-11-18 17:56 UTC, merged