Add rke2 support for drain before delete
rancher/rancher pull request #35957
Opened 2021-12-22 21:58 UTC by jakefhyde

## Description

CAPI (cluster API) drains nodes on deletion by default, although it is possible to force a node not to drain by adding the `ExcludeNodeDrainingAnnotation` annotation (e.g.  `machine.cluster.x-k8s.io/exclude-node-draining: true`). This PR adds that annotation to the `MachineTemplateSpec` in the `MachineDeployment`, which will apply to each machine created. This creates parity with RKE1 "Drain Before Delete", by allowing users the option to apply a drainage policy to each machine pool.

Related Issue: #35274

2021-12-24 00:37 UTC, thedadams requested changes
Can you add a test in `tests/integration/pkg/tests/machineprovisioning/machine_test.go` for this functionality?

Please reach out if you have questions about the provisioning tests.

2022-01-06 16:48 UTC, jakefhyde commented
@thedadams Ok the tests should pass this time, I was using a function that had since been removed from the testing framework.

2022-01-08 03:50 UTC, thedadams approved these changes

2022-01-10 17:30 UTC, kinarashah approved these changes

2022-01-10 20:15 UTC, merged