Added a fix for service discovery related error.
rancher/rancher pull request #35973
Opened 2021-12-27 11:42 UTC by vivek-infracloud

tests.v3_api.test_service_discovery.test_dns_record_type_multiple_workloads

Above test fails almost always while running the **rancher-v3_ontag_custom_certification**. 
Here is a link to the above failed job. - https://jenkins.int.rancher.io/job/rancher_qa/job/rancher-v3_ontag_custom_certification/77/

In this PR I've added the possible fix for the test failure.

Here is a link to the passing test with the fix - https://jenkins.int.rancher.io/job/rancher_qa/job/rancher-freeform/620/

2021-12-28 17:23 UTC, izaac commented
@vivek-infracloud I see that we're adding a sleep for this, could you elaborate the reasoning behind it.

2021-12-30 10:57 UTC, vivek-infracloud commented
@izaac

While running the network checks, sometimes few errors were coming up related to "test_service_discovery". Adding analysis related to it below :

Generally it errors out during dig command and ping command execution under validate_dns_entry. On further debugging using freeform, found that after svc creation the dig command doesn't giving all the IPs that svc is pointing to. Jenkins logs below:

16:29:56.384  run cmd: 	kubectl --kubeconfig /src/rancher-validation/tests/v3_api/k8s_kube_config exec default-70418-7d9b9bf768-jq8rf -n test-47440 -- dig record-39516.test-47440.svc.cluster.local +short
16:29:56.384  returns: 	b'10.42.247.112\n'
16:29:56.384  dig cmd op---------------->b'10.42.247.112\n'
16:29:56.384  dig expected value---------------->10.42.247.112
16:29:56.384  dig expected value---------------->10.42.247.111
16:29:56.384  FAILED

On manually running the command i was able to get the IPs :

> kubectl  exec default-70418-7d9b9bf768-jq8rf -n test-47440 -- dig record-39516.test-47440.svc.cluster.local +short
10.42.247.112
10.42.247.111

svc endpoints:

> kubectl describe svc record-39516 -n test-47440 | grep -i endpoints
Endpoints:         10.42.247.111:42,10.42.247.112:42

As a work around i added sleep before the dig command and ping command execution and the errors were not coming up.

Analysis is there on confluence page as well.

2021-12-30 15:39 UTC, izaac commented
I was thinking in probably getting the sleep encapsulated in a `retry_dig` function.

2021-12-30 15:40 UTC, izaac requested changes
Added comment. 

Analysis was good but I would prefer to encapsulate the sleep if possible.

2022-01-10 15:56 UTC, izaac approved these changes
I paired with Vivek in a couple of refactoring is LGTM now.

2022-01-10 16:01 UTC, izaac commented
Added @snasovich for review

2022-03-30 05:08 UTC, izaac commented
Please try a rebase the CI code could be out of date in your branch.

2022-03-31 13:44 UTC, izaac commented
@sowmyav27 @anupama2501 this is ready for review and merge please take a look

2022-04-18 07:32 UTC, merged