Go Automation: Harvester provisioning
rancher/rancher pull request #36100
Opened 2022-01-11 00:03 UTC by slickwarren

adding harvester node driver and dependencies

New Yaml options:
```
//below are some of the default values used. values with <> should be pulled from your setup
harvesterCredentials:
     clusterId: <>
     clusterType: "imported"
     kubeconfigContent: <>
harvesterMachineConfig:
  diskSize: "40"
  cpuCount: "2"
  memorySize: "8"
  networkName: <>
  imageName: <>
  vmNamespace: "default"
  sshUser: "ubuntu"
  diskBus: "virtio"
```

this was tested using a harvester setup for 1, 3 node all roles, and 3 node dedicated roles clusters.

2022-01-11 16:02 UTC, igomez06 requested changes

2022-01-11 16:02 UTC, igomez06 commented on tests/v2/validation/provisioning/provisioning_node_driver_test.go
> +	baseHarvesterClusterName = "automationharvester-"
Let's have these all consistent, we can name them all `automation(provider)-` but just keep them consistent

2022-01-11 16:42 UTC, igomez06 approved these changes
Looks good

2022-01-15 02:28 UTC, sowmyav27 approved these changes
LGTM

2022-01-18 17:47 UTC, bmdepesa approved these changes
LGTM

2022-01-18 17:47 UTC, merged