notate the upgraded condition when rancher refusing to upgrade due to…
rancher/rancher pull request #36422
Opened 2022-02-07 17:38 UTC by paynejacob

issue: #36370 

# Problem
When a rke1 cluster node is deleted outside of rancher it marked as unavailable.  If more nodes are deleted than the upgrade strategy permits and newly added nodes fail to register rancher will refuse to provision any new nodes going forward because the upgrade strategy does not permit it.  This is not clear as it is only logged in the provisioning log.

# Solution
Update the upgrade condition message to state why rancher is refusing to upgrade the cluster.

# Testing
tested normal upgrades do not show the status and rancher clearly reports why it is refusing to continue in the ui when too many nodes are unavailable.

2022-02-07 23:45 UTC, thedadams requested changes

2022-02-07 23:45 UTC, thedadams commented on pkg/controllers/management/rkeworkerupgrader/upgrade.go
> +		v32.ClusterConditionUpgraded.Message(cluster, fmt.Sprintf("cluster [%s] worker-upgrade: not enough nodes to upgrade: nodes %v notReady %v maxUnavailable %v",
```suggestion
		v32.ClusterConditionUpgraded.Message(cluster, fmt.Sprintf("cluster [%s] worker-upgrade: maximum node unavailable limit reached: nodes %v notReady %v maxUnavailable %v",
```

2022-02-07 23:45 UTC, thedadams commented on pkg/controllers/management/rkeworkerupgrader/upgrade.go
> +		return fmt.Errorf(v32.ClusterConditionUpgraded.GetStatus(cluster))
I think `GetStatus` returns `True`, `False`, `Unknown`.
```suggestion
		return fmt.Errorf(v32.ClusterConditionUpgraded.GetMessage(cluster))
```

2022-02-07 23:45 UTC, thedadams commented on pkg/controllers/management/rkeworkerupgrader/upgrade.go
> +		return fmt.Errorf(v32.ClusterConditionUpgraded.GetStatus(cluster))
Same comment as above.

2022-02-08 18:26 UTC, paynejacob commented on pkg/controllers/management/rkeworkerupgrader/upgrade.go
>  	if notReady > maxAllowed {
I think it should because you wouldn't want to create a race condition with 2 etcd or controlplane nodes joining at the same time?

2022-02-08 18:28 UTC, kinarashah commented on pkg/controllers/management/rkeworkerupgrader/upgrade.go
>  	if notReady > maxAllowed {
The skipNode skips all etcd or controlplane nodes, this logic is only for worker nodes

2022-02-08 18:37 UTC, paynejacob commented on pkg/controllers/management/rkeworkerupgrader/upgrade.go
>  	if notReady > maxAllowed {
The skipNode function you linked is already filtering out provisioning nodes https://github.com/rancher/rancher/blob/ee1e06dac9db8e50f9d9208df2cc569d756e2e57/pkg/controllers/management/rkeworkerupgrader/node.go#L119

2022-02-08 18:54 UTC, kinarashah commented on pkg/controllers/management/rkeworkerupgrader/upgrade.go
>  	if notReady > maxAllowed {
Yep, that's why I don't see how `notReady > maxAllowed` is satisfied if the provisioning nodes are already skipped and not counted in notReady. Provisioning nodes weren't meant to be part of upgrade process cuz their plans don't need to updated

2022-02-10 02:23 UTC, thedadams submitted a review, later dismissed

2022-02-15 18:35 UTC, closed without merging