foreground deletion on node-cleanup-job
rancher/rancher pull request #36656
Opened 2022-02-25 22:50 UTC by jakefhyde

Forwardport of https://github.com/rancher/rancher/pull/36398
https://github.com/rancher/rancher/issues/36645

2022-02-28 15:29 UTC, paynejacob submitted a review, later dismissed

2022-02-28 16:18 UTC, thedadams requested changes
There was another commit later to fix an issue with this implementation.

https://github.com/rancher/rancher/pull/36236

2022-02-28 22:48 UTC, thedadams approved these changes

2022-03-01 19:09 UTC, kinarashah approved these changes

2022-03-01 19:11 UTC, merged