ensure the rbac finalizer is the last finalizer to be removed
rancher/rancher pull request #36706
Opened 2022-03-01 22:42 UTC by paynejacob

#35899 

# Problem
When a cluster is deleted the rbac is deleted before the cluster finishes deleting.  This prevents standard users from seeing the resource delete event and can hide clusters that encounter errors deleting.

# Solution
Delete rbac as the last finalizer to ensure the cluster deleted correctly before deleting it.

2022-03-01 22:47 UTC, Oats87 submitted a review, later dismissed

2022-03-01 22:51 UTC, jakefhyde submitted a review, later dismissed

2022-03-01 23:20 UTC, thedadams requested changes

2022-03-01 23:20 UTC, thedadams commented on pkg/controllers/management/auth/project_cluster_handler.go
> +		return obj, errors.New("waiting to be the last finalizer")
Can we use `generic.ErrSkip` instead so a log doesn't get out and we push retry to its max value.

2022-03-02 21:11 UTC, thedadams approved these changes

2022-03-03 16:39 UTC, jakefhyde submitted a review, later dismissed

2022-03-03 17:33 UTC, Oats87 approved these changes

2022-03-03 18:09 UTC, thedadams approved these changes

2022-03-03 19:46 UTC, merged