Fix node deletion in RKE2 cluster
rancher/rancher pull request #36990
Opened 2022-03-21 23:11 UTC by jiaqiluo

Issue: GH-36727

Problem:
The v1 Node is not deleted when a CAPI Machine is deleted in the cluster manager UI.

Solutions:
1. Add the missing CAPI label "cluster.x-k8s.io/control-plane" to the control plane node. Otherwise, we cannot remove a node because of the errNoControlPlaneNodes error.
2. Delete the CAPI Machines which have the control plane role and are managed by an RKEControlPlane object. The deletion of the RKEControlPlane object is triggered by the deletion of the CAPI cluster.

2022-03-21 23:44 UTC, jakefhyde approved these changes

2022-03-22 01:23 UTC, thedadams requested changes

2022-03-22 01:23 UTC, thedadams commented on pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go
> +				_ = h.machineClient.Delete(machine.Namespace, machine.Name, &metav1.DeleteOptions{})
We shouldn't ignore the error.

2022-03-24 00:23 UTC, jiaqiluo commented on pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go
> +				_ = h.machineClient.Delete(machine.Namespace, machine.Name, &metav1.DeleteOptions{})
fixed.

2022-03-24 12:40 UTC, thedadams approved these changes

2022-03-24 12:40 UTC, thedadams commented on pkg/controllers/provisioningv2/rke2/rkecontrolplane/controlplane.go
> +					return "", err
nit:
```suggestion
					return "", fmt.Errorf("error deleting machine %s/%s: %v", machine.Namespace, machine.Name, err)
```

2022-03-24 15:53 UTC, jakefhyde approved these changes

2022-03-24 16:18 UTC, jakefhyde submitted a review, later dismissed

2022-03-24 17:51 UTC, jakefhyde approved these changes

2022-03-24 17:52 UTC, merged