[DO NOT MERGE UNTIL RELEASE] Aligned Rancher System Charts Default Branch from Dev to Release
rancher/rancher pull request #37053
Opened 2022-03-25 21:09 UTC by eliyamlevy

Moved the rancher charts operators to point to release instead of dev as outlined in [this document](https://confluence.suse.com/pages/viewpage.action?pageId=949584400). 

Do not merge this PR until the release captain is ready.

Parent Issue: https://github.com/rancher/rancher/issues/36376

2022-03-25 21:20 UTC, SheilaghM approved these changes

2022-03-25 21:36 UTC, paynejacob requested changes
fleet and rancher webhook are still pinned to pre-releases. These will need to be released and updated before we can merge this.

2022-03-28 22:06 UTC, paynejacob approved these changes
fleet and webhook will be merged in a separate pr.

2022-03-29 23:51 UTC, paynejacob commented
closing in favor of https://github.com/rancher/rancher/pull/37055

2022-03-29 23:51 UTC, closed without merging