Fix SAML unauthorized log message
rancher/rancher pull request #37417
Opened 2022-04-20 21:53 UTC by cmurphy

`err` is checked for nil on the lines above and is guaranteed to be nil
in this log message, so don't use it. Add more wording to indicate that
it could be a group membership problem and to align better with the
wording in the UI.

SURE-4509

2022-04-20 22:05 UTC, cbron approved these changes
lgtm, err will always be nil

2022-04-21 13:23 UTC, MbolotSuse approved these changes
~~LGTM~~

2022-04-21 13:26 UTC, MbolotSuse requested changes
One question on including in Identifier for the user in the log message.

2022-04-21 18:08 UTC, cmurphy commented on pkg/auth/providers/saml/saml_client.go
> +		log.Errorf("SAML: User is not an authorized user or is not a member of an authorized group")
done

2022-04-21 18:09 UTC, MbolotSuse approved these changes
LGTM

2022-04-21 18:17 UTC, cbron approved these changes
lgtm, shouldn't error out based on diff cases of the name being nil or whatever

2022-04-22 16:08 UTC, merged