Set local k8s 1.23.3
rancher/rancher pull request #37453
Opened 2022-04-22 21:24 UTC by jiaqiluo

Issue: https://github.com/rancher/rancher/issues/37432
Set local k8s 1.23.3 by reverting  8cb05b08

2022-04-26 16:58 UTC, kinarashah approved these changes

2022-05-02 22:29 UTC, snasovich requested changes
There is now `v1.23.6-k3s1` (https://github.com/k3s-io/k3s/releases/tag/v1.23.6%2Bk3s1) so we should use at least it.

Note that I've confirmed with RKE2 team they are working on releasing `v1.23.6-rke2r2`, but there won't be `v1.23.6-k3s2` so we're safe to go to `v1.23.6-k3s1` and don't need to wait for anything newer for Rancher v2.6.5.

2022-05-03 18:28 UTC, snasovich approved these changes

2022-05-04 17:37 UTC, jakefhyde approved these changes

2022-05-04 17:38 UTC, annablender approved these changes

2022-05-04 17:43 UTC, merged