Properly correlate local snapshot to node when cloudprovider changes …
rancher/rancher pull request #37649
Opened 2022-05-09 21:09 UTC by Oats87

https://github.com/rancher/rancher/issues/37641

Upon etcd snapshot restore, a local snapshot node name was blindly trusted as the node to designate. This is not a valid procedure, as we must ensure we correlate the snapshot to the correct machine rather than the node that is listed from the config map in the snapshot. 

This is primarily due to the cloud provider being able to change node names, which can cause problems down the line for restore.

2022-05-09 21:30 UTC, jiaqiluo approved these changes
LGTM

2022-05-10 00:01 UTC, thedadams requested changes

2022-05-10 00:01 UTC, thedadams commented on pkg/provisioningv2/rke2/planner/etcdrestore.go
> +			return fmt.Errorf("unable to retrieve nodeName for machine on snapshot: %s/%s", snapshot.Namespace, snapshot.Name)
```suggestion
			return fmt.Errorf("unable to retrieve nodeName for machine on snapshot %s/%s: %v", snapshot.Namespace, snapshot.Name, err)
```

2022-05-10 00:12 UTC, Oats87 commented on pkg/provisioningv2/rke2/planner/etcdrestore.go
> +			return fmt.Errorf("unable to retrieve nodeName for machine on snapshot: %s/%s", snapshot.Namespace, snapshot.Name)
done

2022-05-10 00:13 UTC, thedadams approved these changes

2022-05-10 00:36 UTC, jiaqiluo approved these changes

2022-05-10 06:08 UTC, merged