Added system agent uninstall script to assets
rancher/rancher pull request #37941
Opened 2022-06-08 17:28 UTC by jakefhyde

Rancher component for https://github.com/rancher/rancher/issues/37283

Added system agent uninstall script to rancher assets. Since the install script installs the uninstall script, the only required change is to the Dockerfile.

Depends on https://github.com/rancher/system-agent/pull/82 and subsequent system-agent `v0.2.8` release.

2022-06-17 17:31 UTC, annablender submitted a review, later dismissed
LGTM. Build is funky though

2022-06-23 12:54 UTC, phillipsj requested changes
Can you add the Wins uninstall too? We call it CATTLE_WINS_AGENT and it is on line 59.

Uninstall script: https://github.com/rancher/wins/blob/main/uninstall.ps1

2022-06-24 00:41 UTC, phillipsj submitted a review, later dismissed

2022-06-24 13:10 UTC, phillipsj submitted a review, later dismissed

2022-06-24 16:30 UTC, phillipsj submitted a review, later dismissed

2022-06-24 21:15 UTC, phillipsj approved these changes

2022-06-24 21:50 UTC, annablender approved these changes

2022-06-24 21:50 UTC, annablender commented
Approved pending CI

2022-06-27 14:40 UTC, phillipsj approved these changes

2022-07-05 14:57 UTC, closed without merging