Fixed etcd-only plans always in sync post-prepare
rancher/rancher pull request #38065
Opened 2022-06-22 21:09 UTC by jakefhyde

Issue: https://github.com/rancher/rancher/issues/38064

 
# Problem

Cluster with etcd only nodes require the etcd nodes to be restarted during encryption key rotation before restarting the control plane nodes.

# Solution

 
There was a bug in rancher's encryption key rotation implementation where etcd nodes would not be restarted on subsequent iterations, because their plans were already in sync. This was fixed by adding an environment variable which utilizes the current control plane encryption key rotation phase to cause the plans to rerun.

# Testing

## Engineering Testing
### Manual Testing

Tested the following cases:
#### v1.23.7-k3s-4dda76b0
configuration | status
-|-
1 node all roles | ✔️
1 etcd, 1 cp, 1 worker | ✔️
3 nodes all roles | ✔️
3 etcd, 2 cp, 3 worker | ✔️
3 etcd, 3 cp, 3 worker | ✔️
3 etcd, 5 cp, 3 worker | ✔️
### Automated Testing

## QA Testing Considerations

 
This realistically should be tested with varying cloud providers, and varying kubernetes versions. Currently, my testing only covers the 1.23 release line for k3s, however these changes are not in the latest KDM release for rancher, so while this will hit rancher for v2.6.6, encryption key rotation may be enabled OOB.

### Regressions Considerations

Encryption key rotation has the potential to break everything, so try to mess with the cluster as much as possible.

2022-06-23 12:49 UTC, phillipsj approved these changes

2022-06-23 20:28 UTC, rosskirkpat approved these changes

2022-06-24 00:39 UTC, phillipsj requested changes
Can we split the go mod and sum changes into a separate commit from the code changes?

2022-06-24 03:47 UTC, phillipsj approved these changes

2022-06-24 18:41 UTC, annablender approved these changes
High level

2022-06-24 19:35 UTC, Oats87 approved these changes

2022-06-24 20:47 UTC, merged