Removed hardcoded value for machine pools to allow users to increase …
rancher/rancher pull request #38124
Opened 2022-06-28 20:39 UTC by thaneunsoo

…node count in the pool. Changed config struct to allow for NodesAndRoles to accept quantity as a value. Adjusted all tests using RKEMachinePoolSetup helper function to adjust to the new structure.

2022-06-28 22:23 UTC, igomez06 reviewed
Looks really good, just some nitpicks then I'll give it my approval

2022-06-28 22:23 UTC, igomez06 commented on tests/framework/extensions/machinepools/machinepools.go
> +//     Worker:       false,
Can you fix the indentation please

2022-06-28 22:23 UTC, igomez06 commented on tests/framework/extensions/machinepools/machinepools.go
> +//     Worker:       false,
Same here. no big deal just a nit pick

2022-06-28 22:23 UTC, igomez06 commented on tests/v2/validation/provisioning/rke2/custom_cluster_test.go
> +		if nodes.ControlPlane == true {
You don't have to do the '==' you can just do `if nodes.ControlPlane` less verbose that way

2022-06-29 20:11 UTC, slickwarren requested changes

2022-06-29 20:13 UTC, igomez06 commented on tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go
> +func TestProvisioningTestSuite(t *testing.T) {
I agree

2022-06-30 18:03 UTC, igomez06 approved these changes
Looks good Tim, great job

2022-06-30 22:20 UTC, sowmyav27 requested changes

2022-06-30 22:20 UTC, sowmyav27 commented on tests/v2/validation/provisioning/README.md
I think this statement in the readme file will have to be changed? `nodes are divided by "|"` ?

2022-07-01 16:30 UTC, igomez06 commented on tests/v2/validation/provisioning/README.md
> +provisioningInput is needed to the run the RKE2 tests, specifically kubernetesVersion, cni, and providers. nodesAndRoles is only needed for the TestProvisioningDynamicInput test, node pools are divid
Can you actually mention that is a list of objects separated by a comma. There is a slight mistake, but can you update it where it says `nodeProviders is only needed for custom cluster test` and change it to `nodeProviders is only needed for node provider cluster tests`

2022-07-01 16:51 UTC, igomez06 commented
Tim why are all the go.mod files updated?

2022-07-01 17:07 UTC, igomez06 submitted a review, later dismissed

2022-07-07 15:41 UTC, markusewalker approved these changes
LGTM.

2022-07-07 15:59 UTC, sowmyav27 commented on tests/v2/validation/provisioning/README.md
After an offline discussion - Can we change it to something like `“{nodeRoles : True/false, Quantity: <qty>},”`

2022-07-07 17:04 UTC, sowmyav27 approved these changes

2022-07-07 21:02 UTC, merged