remove_psp_in_cis_mode_for_k3s_v1.25
rancher/rancher pull request #38759
Opened 2022-08-29 21:01 UTC by ShylajaDevadiga

## Issue: 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2022-08-30 20:45 UTC, rancher-max reviewed
Is it possible to strip out the PSP stuff from the original `policy.yaml` into its own file, and then instead of having a separate `v125_policy.yaml`, we just use `policy.yaml` for both and then apply the different PSP/PS yaml for v1.24-/v1.25+ depending on installed version?

Also, I wonder if `kube-apiserver-arg` of `'enable-admission-plugins=NodeRestriction,NamespaceLifecycle,ServiceAccount'` needs to include `PodSecurity`? I see it's enabled by default in v1.25 per https://kubernetes.io/docs/concepts/security/pod-security-admission/. It might also be enabled by default as far back as v1.22. It should at least be acceptable as an admission plugin there. 

This will get a little bit more confusing though because in 1.22, 1.23, and 1.24 we should still need to pass the PodSecurityPolicy admission plugin for the PodSecurityPolicy manifests in the policy.yaml to apply successfully I think.

2022-08-31 06:44 UTC, ShylajaDevadiga commented
PodSecurityAdmission is enabled by default. So I believe we don't need to include the PodSecurity plugin in the kube-apiserver-arg explicitly and we pass the configuration file used by the Pod Security Admission Controller to set different PodSecurity standards like privileged, baseline or restricted.

2022-08-31 18:51 UTC, galal-hussein reviewed
just one comment

2022-08-31 18:51 UTC, galal-hussein commented on tests/validation/tests/v3_api/resource/terraform/k3s/master/install_k3s_master.sh
> +  if [[ "${4}" == *"v1.25"*  ]]
we should update this to include any new minor version, i.e " >= 1.25"

2022-08-31 21:19 UTC, dereknola approved these changes

2022-09-21 15:44 UTC, rancher-max requested changes

2022-09-21 15:44 UTC, rancher-max commented on tests/validation/tests/v3_api/resource/terraform/k3s/master/install_k3s_master.sh
> +    yum -y install bc
We should only install this based on OS, not necessarily if the selinux param is passed in config.

2022-09-21 15:44 UTC, rancher-max commented on tests/validation/tests/v3_api/resource/terraform/k3s/master/join_k3s_master.sh
> +    yum -y install bc
Same here: We should only install this based on OS, not necessarily if the selinux param is passed in config.

2022-09-23 23:21 UTC, ShylajaDevadiga commented
Closing in favor on new PR

2022-09-23 23:21 UTC, closed without merging