[v2.7] add cgroupv2 script for k3s
rancher/rancher pull request #38924
Opened 2022-09-15 01:20 UTC by kinarashah

Adding script to entrypoint per https://github.com/rancher/rancher/issues/36238#issuecomment-1222658982 to support cgroups v2. This will allow running docker install out of the box without user changes.

2022-09-15 01:44 UTC, jakefhyde submitted a review, later dismissed

2022-09-15 03:06 UTC, jiaqiluo approved these changes

2022-09-15 03:17 UTC, brandond approved these changes

2022-09-15 03:21 UTC, brandond requested changes

2022-09-15 03:21 UTC, brandond commented on package/entrypoint.sh
> +  busybox-static xargs -rn1 < /sys/fs/cgroup/cgroup.procs > /sys/fs/cgroup/init/cgroup.procs || :
I don't think we need busybox-static just for xargs. We're already running in in BCI which has xargs from the `findutils` package.

```suggestion
  xargs -rn1 < /sys/fs/cgroup/cgroup.procs > /sys/fs/cgroup/init/cgroup.procs || :
```

2022-09-15 03:21 UTC, brandond commented on package/Dockerfile
> +RUN zypper -n install git-core curl ca-certificates unzip xz gzip sed tar shadow gawk vim netcat-openbsd mkisofs busybox-static && \
```suggestion
RUN zypper -n install git-core curl ca-certificates unzip xz gzip sed tar shadow gawk vim netcat-openbsd mkisofs && \
```

2022-09-16 22:49 UTC, brandond approved these changes

2022-09-16 23:57 UTC, jiaqiluo approved these changes

2022-09-17 01:44 UTC, merged

2022-09-17 01:57 UTC, brandond commented
Would love to see this backported to 2.6 as well, if not also 2.5. Folks are having problems with this now that several distros default to cgroupv2.

2022-09-17 01:59 UTC, kinarashah commented
@brandond Yeah, I agree. I have a backport PR open that'll update and will go into v2.6.9.