Bump steve version
rancher/rancher pull request #39156
Opened 2022-09-28 21:15 UTC by MbolotSuse

Related to rancher/rancher#38330. This required a change in steve, so I am pulling in steve ot the newest version available in steve's master branch.

2022-09-28 21:39 UTC, maxsokolovsky approved these changes

2022-09-28 23:53 UTC, rmweir requested changes
Did you run go mod tidy?

2022-09-29 16:26 UTC, maxsokolovsky approved these changes

2022-09-29 17:53 UTC, rmweir approved these changes

2022-09-29 17:54 UTC, merged