Bump system-agent and wins
rancher/rancher pull request #39263
Opened 2022-10-10 16:25 UTC by jakefhyde

Bump system-agent & wins for https://github.com/rancher/rancher/issues/39068

2022-10-10 21:15 UTC, Oats87 requested changes
What is the go mod bump for? Do we need to do this in this PR?

2022-10-10 21:49 UTC, Oats87 approved these changes

2022-10-11 19:04 UTC, HarrisonWAffel approved these changes

2022-10-11 19:05 UTC, jiaqiluo approved these changes

2022-10-11 19:12 UTC, merged