Adds mirrored images for bci-micro and bci-busybox.
rancher/rancher pull request #39419
Opened 2022-10-26 17:38 UTC by KevinJoiner

Issue: https://github.com/rancher/rancher/issues/35587

2022-10-26 19:10 UTC, jiaqiluo requested changes
~Because [registry.rancher.com](http://registry.rancher.com/) is an alias of [registry.suse.com](http://registry.suse.com/), what we need to do is replace `registry.suse.com` with `registry.rancher.com`~ 

Please ignore this comment. We still need to mirror those images, so the changes in the PR are valid.

2022-10-26 19:50 UTC, cbron reviewed
two nits, and needs images mirrored, then good

2022-10-26 19:50 UTC, cbron commented on pkg/image/utilities/utilities_test.go
> +			t.Logf("did not expected error when checking image %s", k)
```suggestion
			t.Logf("did not expect error when checking image %s", k)
```

2022-10-26 19:50 UTC, cbron commented on pkg/image/utilities/utilities_test.go
> +			t.Logf("expect error when checking image %s", k)
```suggestion
			t.Logf("expected error when checking image %s", k)
```

2022-10-26 23:11 UTC, cbron commented on pkg/image/resolve.go
> +		addSourceToImage(imagesSet, "rancher/mirrored-bci-micro:15.4.14.3", coreLabel)
both of these exist now

2022-10-26 23:12 UTC, cbron approved these changes

2022-10-27 16:17 UTC, jiaqiluo approved these changes

2022-10-27 16:26 UTC, cbron approved these changes

2022-10-27 17:15 UTC, merged