Adding permission for project owners to modify podsecuritypolicytemplateprojectbindings
rancher/rancher pull request #39517
Opened 2022-11-07 18:00 UTC by crobby

Added podsecuritypolicytemplateprojectbindings.management.cattle.io permissions to the set of rules that are added to the project-owner rolebinding.

## Issue: 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2022-11-15 14:23 UTC, KevinJoiner requested changes
Missing `prtb_handler_test.go`

2022-12-16 12:29 UTC, crobby commented
This PR is no longer needed

2022-12-16 12:29 UTC, closed without merging

2022-12-23 13:47 UTC, eumel8 commented
@crobby Why is this the case?

2022-12-23 14:48 UTC, crobby commented
It was decided that project owners should NOT have the ability to chage PSP for projects that they own.  PSP modifications are considered an admin function by design.

2022-12-23 15:15 UTC, eumel8 commented
This makes sense. But I got still this error on project member management while adding a new account in Rancher 2.6.9:

```
error creating binding: Forbidden 403: podsecuritypolicytemplateprojectbindings.management.cattle.io is forbidden: User "u-uv5rdttdl4" cannot create resource "podsecuritypolicytemplateprojectbindings" in API group "management.cattle.io" in the namespace "c-fxzb9"
```

My idea was this would solved here.