[v2.7] Fixed intermittent failure with TestCreateNamespaceProjectMember test case
rancher/rancher pull request #39720
Opened 2022-11-28 21:08 UTC by igomez06

## Issue: 
 
https://github.com/rancher/rancher/issues/39710
 
## Problem
 
There was a bit of a timing issue when adding a `project-member` role to a user in order to create a namespace, where the `project-member` role is not fully set causing a `Resource type [namespace] is not creatable` error. 
## Solution

 I added two extra checks to make sure the ProjectRoleTemplateBinding is successfully created.
## Testing

CI drone tests pass.
## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2022-11-28 22:41 UTC, caliskanugur submitted a review, later dismissed
Looks good to me

2022-11-29 06:46 UTC, superseb submitted a review, later dismissed

2022-11-29 19:08 UTC, igomez06 commented
Pushed up one more check, this is to ensure the service account secret is properly created in order for a project member to create a namespace.

2022-11-30 09:45 UTC, superseb requested changes
CI is failing

2022-12-03 09:18 UTC, superseb approved these changes

2022-12-07 21:28 UTC, caliskanugur approved these changes

2022-12-08 15:07 UTC, merged