[2.7] SLE BCI update to 15.4
rancher/rancher pull request #39767
Opened 2022-12-02 20:36 UTC by dirkmueller

## Problem

Rancher and Rancher Agent is currently based on SLE BCI 15 SP3, which goes out of general support on 2022-12-31. 

## Solution

For about half a year there is already SLE BCI 15 SP4 available, so switch to that. 

Also small optimisation on size by using vim-small only instead of full vim in the image.

2022-12-07 11:36 UTC, dirkmueller commented on package/Dockerfile
>  FROM registry.suse.com/bci/bci-base:15.3
I can not do it right away as it fails the CI (something with cgroups, haven't had a chance to debug it)

2022-12-07 11:36 UTC, dirkmueller commented
> @dirkmueller thanks for creating this PR. Besides the comment above, can you also please open the same PR against `release/v2.6` branch?

right away or when this one got merged?

2022-12-07 16:06 UTC, superseb commented on package/Dockerfile
>  FROM registry.suse.com/bci/bci-base:15.3
@dirkmueller Do you have the logs or the Drone run that showed it? It makes the most sense to update all of these at once.

2022-12-08 08:40 UTC, superseb requested changes
@dirkmueller I tested a PR yesterday with both images bumped to 15.4 and it passed. Can you update this PR?

2022-12-09 17:23 UTC, dirkmueller commented
@superseb okay, pushed.

2022-12-10 09:26 UTC, superseb approved these changes
Package diff is;

```
-libgdbm4-1.12-1.418.x86_64
-perl-5.26.1-150300.17.11.1.x86_64
-vim-9.0.0814-150000.5.28.1.x86_64 (replaced by vim-small)
```

2022-12-10 16:01 UTC, macedogm commented
> right away or when this one got merged?

@dirkmueller it can be done now, we don't need to wait of this PR to be merged..

2022-12-10 16:02 UTC, macedogm approved these changes

2022-12-12 17:31 UTC, dirkmueller commented on package/Dockerfile
>  FROM registry.suse.com/bci/bci-base:15.3
it appears to be passing now, so whatever it was, it is no longer relevant.

2022-12-12 17:34 UTC, dirkmueller commented
> > right away or when this one got merged?
> @dirkmueller it can be done now, we don't need to wait of this PR to be merged..


Created backport under https://github.com/rancher/rancher/pull/39866 . this one does not include the vim optimization as it is sort of irrelevant for the core issue.

2022-12-13 08:59 UTC, dirkmueller commented
just in case it isn't obvious, I do not have merge rights

2022-12-13 09:04 UTC, merged