Add CAPI predicates to RKEBoostrap
rancher/rancher pull request #39871
Opened 2022-12-12 22:45 UTC by jakefhyde

## Issue: 

Part of groundwork for #39139

## Problem

We need a mechanism to support pausing the various CRs in our CAPI implementation, so we can disable cluster reconciliation during disruptive actions such as encryption key rotation.

## Solution

Add missing predicates to rke bootstrap controller, including checking for pausing as well as other required predicates we were missing.

https://cluster-api.sigs.k8s.io/developer/providers/bootstrap.html?highlight=bootstrap#bootstrap-provider-specification

**Note:** there are some predicates which have been added, which do not appear in the upstream docs as requirements, however these predicates (for example, checking if `capiCluster.Status.InfrastructureReady == false`) are added because although we functionally always set `InfrastructureReady = true`, bootstrapping before the cluster is ready is not desired and is subject to change in the future.

2023-01-03 17:38 UTC, Oats87 requested changes

2023-01-03 17:38 UTC, Oats87 commented on pkg/controllers/provisioningv2/rke2/rkebootstrap/controller.go
> -package bootstrap
I would prefer we do not rename packages at this time. It makes maintenance very difficult. We'll be much better off doing this once we've stabilized our code base.

2023-01-03 22:03 UTC, annablender commented on pkg/controllers/provisioningv2/rke2/bootstrap/controller.go
> +	if apierrors.IsNotFound(err) {
This is fine the way you have it. I feel like it's more `Go style` for error handling but personally, I'd put the `IsNotFound` checks inside the `err != nil` blocks. That makes more logical sense but again I see the efficiency of short circuiting here

2023-01-03 22:04 UTC, annablender submitted a review, later dismissed

2023-01-03 22:43 UTC, HarrisonWAffel submitted a review, later dismissed
This looks good and matches the conditions within the CAPI docs

2023-01-04 03:10 UTC, Oats87 requested changes

2023-01-04 03:10 UTC, Oats87 commented on pkg/controllers/provisioningv2/rke2/bootstrap/controller.go
> +	apierrors "k8s.io/apimachinery/pkg/api/errors"
this is imported already

2023-01-05 17:48 UTC, HarrisonWAffel approved these changes

2023-01-09 22:06 UTC, HarrisonWAffel approved these changes

2023-01-09 23:43 UTC, Oats87 approved these changes
LGTM!

2023-01-09 23:43 UTC, merged