Refactor planner handler and add capi predicates
rancher/rancher pull request #40083
Opened 2023-01-06 04:00 UTC by jakefhyde

## Issue: 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2023-01-10 22:28 UTC, annablender commented
@jakefhyde Could you fill out the PR template? Has this been smoke tested?

2023-01-11 23:58 UTC, Oats87 requested changes
Overall LGTM; however I have a few functionality concerns (Around upgrades)

2023-01-11 23:58 UTC, Oats87 commented on pkg/controllers/provisioningv2/rke2/planner/controller.go
> +			rke2.Reconciled.Message(&status, "reconciling control plane")
technically, if we're waiting we could be reconciling the worker nodes as well. this will lead to user confusion imo

2023-01-11 23:58 UTC, Oats87 commented on pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go
> -	encryptionKeyRotationLeaderAnnotation = "rke.cattle.io/encrypt-key-rotation-leader"
what happens if a user updates from an annotation version of Rancher to a status version of Rancher in the middle of an encryption key rotation?

2023-01-11 23:58 UTC, Oats87 commented on pkg/provisioningv2/rke2/planner/planner.go
> +func detailMessage(machines []string, messages map[string][]string) string {
sp: detail -> detailed?

2023-01-12 16:49 UTC, HarrisonWAffel approved these changes

2023-01-13 17:05 UTC, Oats87 approved these changes

2023-01-13 17:32 UTC, merged