Wait for probes during encryption key rotation restart
rancher/rancher pull request #40206
Opened 2023-01-18 23:52 UTC by jakefhyde

## Issue:  #38283

 
## Problem

With the removal of the killall script, some resources are left over after restarting the `rke2-server/k3s` services during encryption key rotation.

## Solution

Wait for probes after restarting the nodes to ensure the nodes are actually healthy and ready to receive API requests.

## Testing

## Engineering Testing
### Manual Testing

Tested manually with a freshly provisioned single node cluster.

### Automated Testing

Tested with a freshly provisioned single node cluster, then again with 10k secrets.
Tested with a freshly provisioned 3 etcd + 2 controlplane + 3 worker cluster, then again with 10k secrets.

## QA Testing Considerations

During testing, https://github.com/rancher/rke2/issues/3801 was discovered. This issue is unrelated to rancher, but will not be fixed until a future release of k3s/rke2. If this bug is encountered during encryption key rotation, there is no recourse except for an etcd restore, but this issue occurs intermittently.

### Regressions Considerations

2023-01-19 00:52 UTC, Oats87 requested changes

2023-01-19 00:52 UTC, Oats87 commented on pkg/provisioningv2/rke2/planner/encryptionkeyrotation.go
> +	nodePlan.Probes = probes
Is there any way we can refactor probe generation to not require this giant preamble every time we need the probes for a node...?

2023-01-20 18:55 UTC, Oats87 approved these changes

2023-01-20 19:04 UTC, HarrisonWAffel approved these changes

2023-01-20 19:36 UTC, merged