2.6 rancher updates
rancher/rancher pull request #40243
Opened 2023-01-23 13:21 UTC by KevinJoiner

2023-01-23 17:37 UTC, rmweir requested changes
Can you remove 0402678ab57d4a6878ccf0a9c53fe38f5e66ae56 5a56a94923c367eba553824c9beebb59243dfae5 and their corresponding commits in the other two PRs? We do not want these changes for final release.

2023-01-23 22:57 UTC, macedogm commented on package/Dockerfile
> +ENV CATTLE_FLEET_MIN_VERSION=100.2.0+up0.5.0
Update the version following https://github.com/rancher/charts/pull/2346/files#diff-1d00b840e705f8e431bd805362d77aeda19db7c216857eac7bf94c28a0478d13R15

```suggestion
ENV CATTLE_FLEET_MIN_VERSION=100.2.0+up0.5.1
```

2023-01-24 04:38 UTC, macedogm approved these changes

2023-01-24 04:38 UTC, cbron approved these changes
lgtm

2023-01-24 04:38 UTC, cbron commented on package/Dockerfile
> +ENV CATTLE_RANCHER_WEBHOOK_MIN_VERSION=1.0.7+up0.2.8
confirmed both of these

2023-01-24 04:38 UTC, cbron commented on pkg/apis/go.mod
> +	github.com/rancher/wrangler v1.0.2
confirmed

2023-01-24 04:51 UTC, rmweir commented
Mentioned UI changes that don't have a corresponding release in ember and dashboard. Going to move forward for now.

2023-01-24 04:52 UTC, rmweir approved these changes

2023-01-24 04:52 UTC, merged