Pass PSP enablement value from rancher chart to webhook chart
rancher/rancher pull request #40367
Opened 2023-01-27 20:49 UTC by maxsokolovsky

## Issue: https://github.com/rancher/rancher/issues/40328
 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2023-01-27 21:39 UTC, crobby commented on pkg/controllers/dashboard/chart/chart.go
> +	PSPEnablement    = "pspEnablement"
nit, should probably have a comment for the constant

2023-01-30 16:11 UTC, crobby commented on package/Dockerfile
> +ENV CATTLE_RANCHER_WEBHOOK_MIN_VERSION=2.0.2+up0.3.2-rc12
rc14 is all the rage nowadays

2023-01-30 20:38 UTC, crobby reviewed
This looks right to me.  Do we need any tests added?

2023-01-30 21:11 UTC, KevinJoiner requested changes
Looks good. It should be quick to add on to the current unit tests in charts_test.go

2023-01-31 18:50 UTC, maxsokolovsky commented
@KevinJoiner, @crobby, I am a little concerned about this handler code that runs on repo change.
https://github.com/rancher/rancher/blob/9bb8d5674d4f2fe85cca799b07a6d18eee257b9e/pkg/controllers/dashboard/systemcharts/controller.go#L51
https://github.com/rancher/rancher/blob/9bb8d5674d4f2fe85cca799b07a6d18eee257b9e/pkg/controllers/dashboard/systemcharts/controller.go#L74

Not sure I understand what this does, but looks like it will replace one of the inner values map. Thus, PSP inner map would be removed. Should this merge maps instead?

2023-02-03 19:09 UTC, crobby approved these changes
lgtm once ci passes

2023-02-06 17:39 UTC, KevinJoiner commented
@maxsokolovsky That code is okay because of the [code that follows ](https://github.com/rancher/rancher/blob/9bb8d5674d4f2fe85cca799b07a6d18eee257b9e/pkg/controllers/dashboard/systemcharts/controller.go#L76-#L80)

The desired behavior is to have the system-default-registry set to the setting if the provided chart does not define the global key. 
So your comment is mostly correct, except the chart definition overrides the hardcoded value, which is why the PSP setting persists.

2023-02-06 17:40 UTC, KevinJoiner approved these changes

2023-02-07 13:09 UTC, crobby commented
Will get this merged...as soon as ci comes back to life.

2023-02-07 20:51 UTC, merged