Update createhascript
rancher/rancher pull request #40642
Opened 2023-02-22 17:26 UTC by anupama2501

## Issue: 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2023-02-23 22:01 UTC, slickwarren requested changes

2023-02-24 01:01 UTC, slickwarren commented on tests/validation/tests/v3_api/test_create_ha.py
> +        helm_rancher_cmd = helm_rancher_cmd + " --set global.cattle.psp.enabled=" + str(RANCHER_PSP_ENABLED).lower()
oh, I misunderstood that this was a new flag too. Ok then this makes sense. Should the default not be `False` then?

2023-02-24 01:21 UTC, anupama2501 commented on tests/validation/tests/v3_api/test_create_ha.py
> +        helm_rancher_cmd = helm_rancher_cmd + " --set global.cattle.psp.enabled=" + str(RANCHER_PSP_ENABLED).lower()
In rancher chart this is by default set to True. Was mimicking that status here as well. So, by default its set to True.

2023-02-24 04:36 UTC, slickwarren approved these changes

2023-03-01 16:54 UTC, markusewalker approved these changes
LGTM

2023-03-02 00:40 UTC, igomez06 approved these changes
LGTM

2023-03-13 15:56 UTC, merged