newimage for sidekick backport
rancher/rancher pull request #40856
Opened 2023-03-13 11:54 UTC by vivek-infracloud

Forward port PR - https://github.com/rancher/rancher/pull/40855

## Issue: 

https://github.com/rancher/qa-tasks/issues/491

## Problem

Sidekick test fails to start nginx container along with ranchertest/mytestcontainer due to port 80 is already occupied.  
 
## Solution

This PR serves the purpose to fix the issue by changing from the nginx container to redis:latest container.

2023-03-13 18:25 UTC, izaac approved these changes
LGTM

2023-03-14 15:01 UTC, markusewalker commented
Seems that in the 2.7 [version](https://github.com/rancher/rancher/pull/40856), there are 5 additional files that are modified. The same would need to be done here, correct?

2023-03-14 15:12 UTC, vivek-infracloud commented
> Seems that in the 2.7 [version](https://github.com/rancher/rancher/pull/40856), there are 5 additional files that are modified. The same would need to be done here, correct?

Right, I am hoping to get the PR approved for the v2.7 first then make same changes in v2.6.

2023-03-14 15:12 UTC, anupama2501 requested changes
Agreed with the comments above! Do we have a jenkins job builder, also for the forward port 2.7, we have changed the image name in multiple places. do we want to update them for 2.6 as well?

2023-03-22 15:25 UTC, markusewalker approved these changes

2023-03-22 15:30 UTC, anupama2501 approved these changes
LGTM

2023-03-23 04:34 UTC, merged