Standalone script for final RC checks
rancher/rancher pull request #40976
Opened 2023-03-24 15:22 UTC by thaneunsoo

This is a standalone script for final RC checks that was previously stored locally and now adding to the repo.

## Issue: 

This script was used for multiple releases for the final RC checks the qa team runs on the final RC. This was part of [qa-task 613](https://github.com/rancher/qa-tasks/issues/613)
 
## Problem

The problem was that this script was floating around internally and there was no actual place the script lived in for others to use when needed.
 
## Solution

Markus created a standalone script directory to hold all the standalone scripts. Adjustments were made to the script to pass arguments into the script while running it.
 
## Testing

## Engineering Testing
### Manual Testing

This script has been used many times for about the past 3 releases to do the final RC checks.

### Automated Testing

This is not a part of Jenkins as it is a standalone script. This script as of now is run manually.

## QA Testing Considerations

In the future, as the framework grows, there is a want to create some sort of system to automate all the existing standalone scripts. 

### Regressions Considerations

There are no regressions with this script as it is just checking values. The only regression would be if any labels were to later change in the future. The script then will be adjusted to match the newly changed labels.

2023-03-24 15:35 UTC, markusewalker commented on tests/scripts/final_rc_checks/final_rc_checks.py
> +# -fqdn FQDN -u Username -p Password -api API_Bearer_token
Tried running locally with `-u` and `-p` but I receive error `final_rc_checks.py: error: unrecognized arguments: -u ... -p ...`. In the comment, can you remove `-u` and `-p`? As specifying only `fqdn` and `-api` worked fine for me.

2023-03-24 15:36 UTC, markusewalker commented on tests/scripts/final_rc_checks/final_rc_checks.py
> +parser.add_argument("-fqdn", "--rancherURL", dest = "fqdn", help="Rancher FQDN e.g. https://ranchertest.qa.rancher.space")
nit; can you just have the help say `help="Rancher FQDN, e.g. https://<Rancher FQDN>"`?

2023-03-24 15:36 UTC, markusewalker commented on tests/scripts/final_rc_checks/final_rc_checks.py
> +print( "fqdn {} api {} ".format(
I would say this part isn't necessary, since you're just printing out the FQDN and api the user just entered.

2023-03-27 18:33 UTC, slickwarren requested changes
I would like to discuss this a little more before approving. 
1. (small thing) - can you squash your commits
2. we should have a discussion as to whether or not we want different languages supported. My opinion would be to stick to only one, and since the existing scripts are bash, this could also easily convert to a bash script. Thoughts? cc @markusewalker @thaneunsoo

2023-03-27 20:38 UTC, slickwarren approved these changes
LGTM

2023-03-27 21:16 UTC, markusewalker approved these changes
LGTM

2023-03-27 21:23 UTC, merged