[v2.6] Adding ssh test to allow check for CPU usage
rancher/rancher pull request #41159
Opened 2023-04-13 17:03 UTC by thaneunsoo

Adding ssh test package to run tests that require ssh to run. Also adjusted downloadsshkeys.go to send a byte instead of string to be used in the node object.

## Issue: 

https://github.com/rancher/qa-tasks/issues/451
 
## Problem

There were tickets around CPU usage being too high and we wanted to add automated checks to more consistently check CPU usage during releases.
 
## Solution

Adding this automation will allow us to more frequently check if the CPU Usage issue were to ever come back. Also with downloadsshkeys.go we are now able to run any ssh related tests within the provisioning package. Currently just added to rke2 package, but since Node object is also used in rke1 and k3s, I will also add there after approval.
 
## Testing

## Engineering Testing
### Manual Testing

Tested the actual ssh command manually multiple times to ensure that it works.

### Automated Testing

Will run jenkins job

## QA Testing Considerations

The CPU check will be stored under the ssh package, and with future additions to that package users can just call the function from the ssh package.
 
### Regressions Considerations

Currently there are no regressions as the ssh key being changed from string to byte is allowing the node object to use the ssh key, which before it wasn't allowed. No other objects are being changed.

2023-04-13 20:00 UTC, slickwarren reviewed
LGTM, do you have a jenkins run for the backport?

2023-04-13 22:54 UTC, markusewalker reviewed
LGTM, like Caleb said, we'll need a Jenkins runs for this as well before approving.

2023-04-13 23:23 UTC, igomez06 reviewed
Looks good I agree with Markus and Caleb about the Jenkins run

2023-04-17 22:30 UTC, igomez06 requested changes
Fix the testing.Ts from 100-101 and fix also could you please fix them on the v2.7 branch.

2023-04-17 22:30 UTC, igomez06 commented on tests/v2/validation/provisioning/rke2/provisioning_node_driver.go
> +		require.NoError(&testing.T{}, err)
Tim this is wrong you need to be using the t that is passed in the function. Can you fix this in the v2.7 branch?

2023-04-17 22:34 UTC, igomez06 commented on tests/v2/validation/provisioning/rke2/provisioning_node_driver.go
> +	assert.NotEmpty(&testing.T{}, nodesList)
Overhear as well, fix these testing.Ts

2023-04-17 23:02 UTC, igomez06 reviewed
Do we want this check for the other cluster types?

2023-07-01 02:10 UTC, closed without merging