Return error when given a non-existent exact version of a system chart
rancher/rancher pull request #41634
Opened 2023-05-22 20:35 UTC by maxsokolovsky

## Issue: related to https://github.com/rancher/rancher/issues/40159
 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2023-05-22 21:12 UTC, MbolotSuse approved these changes
LGTM. I think that this will be difficult to test since this happens async, but I would recommend trying to think of an approach.

2023-05-22 21:14 UTC, MbolotSuse commented
Now that this is returning an error, you will need to update: https://github.com/rancher/rancher/blob/c1175854f8e3a96b7fc39dc8110300ced1f6e186/tests/v2/codecoverage/package/Dockerfile as well, otherwise that probably won't be able to find a valid version.

2023-05-22 21:15 UTC, MbolotSuse requested changes
Needs to update version used in tests as well.

2023-05-23 11:34 UTC, KevinJoiner approved these changes
LGTM with Michaels comment

2023-05-23 15:23 UTC, MbolotSuse approved these changes

2023-05-23 15:23 UTC, MbolotSuse commented on tests/v2/codecoverage/package/Dockerfile
> +ENV CATTLE_RANCHER_WEBHOOK_VERSION=2.0.3+up0.3.3
Ideally this should be the same RC as the main file is on, but I think that this works for now

2023-05-23 17:46 UTC, KevinJoiner approved these changes

2023-05-23 18:00 UTC, merged