Bump rancher-webhook to v0.3.5
rancher/rancher pull request #41777
Opened 2023-06-08 16:07 UTC by JonCrowther

2023-06-08 16:44 UTC, KevinJoiner approved these changes

2023-06-08 17:03 UTC, MbolotSuse requested changes
Please also update the agent's dockerfile: https://github.com/rancher/rancher/blob/c2423288d53210b4f1526e22c9e9ff18de1b24a8/package/Dockerfile.agent#L24

2023-06-09 13:02 UTC, KevinJoiner approved these changes

2023-06-09 13:07 UTC, MbolotSuse approved these changes
Thanks for updating the Agent's dockerfile.

2023-06-09 13:31 UTC, merged