Adding image sources for NeuVector registry adapter and prometheus exporter
rancher/rancher pull request #42102
Opened 2023-07-17 18:19 UTC by selvamt94

To fix rancher/rancher pipeline https://drone-publish.rancher.io/rancher/rancher/10125/5/2

2023-07-17 23:17 UTC, jakefhyde requested changes

2023-07-17 23:17 UTC, jakefhyde commented on pkg/image/origins.go
> +	"mirrored-neuvector-registry-adapter":                     "https://github.com/neuvector/registry-adapter",
According to the logs the missing images are `neuvector-csp-adapter` and `registry-adapter`.

Can you update the origins accordingly?

```
2023/07/17 18:33:05 [ERROR] not all images have a source code origin defined. Please provide origin URL's within rancher/pkg/image/origins.go for the following images: 
neuvector-csp-adapter
registry-adapter
```

2023-07-20 12:37 UTC, macedogm approved these changes

2023-07-21 00:20 UTC, jiaqiluo approved these changes

2023-07-21 03:02 UTC, selvamt94 commented
@macedogm @jiaqiluo @jakefhyde Can one of you please merge this PR.

2023-07-21 10:04 UTC, merged