Bump aks-operator to v1.1.3-rc1
rancher/rancher pull request #42340
Opened 2023-08-07 14:17 UTC by mjura

Issue: https://github.com/rancher/aks-operator/issues/131

2023-08-07 14:29 UTC, Danil-Grigorev requested changes
Please build a tag pointing to the rancher/aks-operator repository. What is the reason for specifying a fork here?

2023-08-07 18:27 UTC, mjura commented
> Please build a tag pointing to the rancher/aks-operator repository. What is the reason for specifying a fork here?

@Danil-Grigorev Updated, I used fork only for test build

2023-08-08 13:06 UTC, Danil-Grigorev approved these changes

2023-08-08 13:17 UTC, furkatgofurov7 approved these changes

2023-08-08 13:17 UTC, furkatgofurov7 commented on pkg/controllers/management/aks/test/buildakscccreateobject.json
> +    "privateDnsZone": null,
Not a blocking, but just confirming: All the below changes due to https://github.com/rancher/aks-operator/pull/243/files being included in the new operator rc release, as I understand this?

2023-08-08 15:22 UTC, merged