Skip clusterdeploy handler if downstream cluster is disconnected
rancher/rancher pull request #43582
Opened 2023-11-20 12:33 UTC by moio

## Issue: https://github.com/rancher/rancher/issues/39597

## Problem
With a disconnected downstream cluster, the `clusterdeploy` handler takes several seconds to time out. This is fine with only a few downstream clusters disconnected, but when the number of disconnected clusters goes over 50 or so, the worker queues will get saturated.

Reason for the slow time out is that the handler may execute code that reaches out to the disconnected downstream cluster - typically `clusterDeploy.getNodeAgentImage` which tries to list `DaemonSets`. That alone can take up to ~30 seconds due to how `TunnelServer`'s `remotedialer` mechanism works.
 
## Solution
Exploit the fact that the `clusterconnected` controller is already marking the cluster status as disconnected. Use that status to exit `clusterdeploy` early in presence of disconnected clusters. Nothing on disconnected clusters can be changed anyway, and trying to read from them is going to fail.

## Testing
See [reproduction steps on the issue](https://github.com/rancher/rancher/issues/39597#issuecomment-1816099261).

## Engineering Testing
Per reproduction steps above (by @moio).

### Manual Testing

This was tested in our production cluster which has a lot (hundreds+) of disconnected clusters and all work queues were blocked. After the patch `cluster-deploy` time went from ~15s down to subsecond. Lasso working queue depth went from *approx amount of disconnected clusters* to 0-1-2.

### Automated Testing
* Test types added/modified:
    * Unit: they cover checking that the main handler logic is not engaged with disconnected clusters, and it is otherwise.

Summary: deemed sufficient by @moio

## QA Testing Considerations

No specific recommendations on fresh and upgrade scenarios.
 
### Regressions Considerations

Clusters should continue to be displayed as available or not available in the UI depending on their connection status, with ~1 minute lag, as before this patch. This is covered by the manual tests above.

## Credits

@erkki for isolating problem and solution.

Supersedes https://github.com/rancher/rancher/pull/43542

2023-11-20 12:38 UTC, moio commented
@snasovich I need you or somebody from your team to take a look at this PR, can you point me to the most appropriate person? Thanks in advance

2023-11-21 20:37 UTC, snasovich commented
@moio , assigned @kinarashah @Oats87 @jakefhyde to review. Thank you!

2023-12-16 05:35 UTC, erkki commented
Crossref https://github.com/rancher/rancher/issues/39597#issuecomment-1858728220 for potential regression

2024-01-17 08:11 UTC, moio commented
> how extensively has this been tested?

@jakefhyde I have been testing this myself, QA instructions are ready.

One customer tested it in a debug image but reported a regression: importing existing AKS clusters would sometimes get stuck and not complete. I tried but failed to reproduce that problem ([details](https://github.com/rancher/rancher/issues/39597#issuecomment-1857824561)).

Another community user [reported a similar problem and I tried to investigate it without coming to a conclusion](https://github.com/rancher/rancher/issues/39597#issuecomment-1858728220).

I would really, really appreciate if you, or anybody else with deeper knowledge, could offer ideas/guidance to move forward and ideally reproduce the problem.

2024-01-17 08:36 UTC, moio commented on pkg/controllers/management/clusterdeploy/clusterdeploy.go
> +		return errors.New("cluster agent not connected")
Addressed as of c3e1b96c2

2024-01-17 19:04 UTC, Oats87 requested changes
@moio yoy may need to check to see if the cluster even needs a dialer, see: https://github.com/rancher/rancher/blob/5314106f746c0c62e95d54922a2dfd116d2f6f68/pkg/dialer/factory.go#L189-L192 

there are specific cluster types where we don't dial using the tunnel dialer

2024-01-18 17:11 UTC, jakefhyde commented
Killed the build since it was stuck waiting for s390x.

2024-02-02 14:09 UTC, moio commented
> @moio yoy may need to check to see if the cluster even needs a dialer, see:
> 
> https://github.com/rancher/rancher/blob/5314106f746c0c62e95d54922a2dfd116d2f6f68/pkg/dialer/factory.go#L189-L192
> 
> there are specific cluster types where we don't dial using the tunnel dialer

I did not know about that part of the code, I learned something, thanks for sharing.

Nevertheless I fail to see how the fact of using a tunnel dialer or not could impact the proposed change in this PR.

Please correct any errors in my reasoning:

1. this patch relies on the `ClusterConditionReady` condition being correctly set
2. the only place in the code where that is set is in [HealthSyncer](https://github.com/rancher/rancher/blob/e4e0fdd7991ef236d3d096e6473f42f26393e08d/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L150-L162), which periodically [attempts to look up a namespace](https://github.com/rancher/rancher/blob/e4e0fdd7991ef236d3d096e6473f42f26393e08d/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L89) as a means to check whether the cluster's API is ready
3. that namespace look up [uses the `HealthSyncer.k8s`](https://github.com/rancher/rancher/blob/e4e0fdd7991ef236d3d096e6473f42f26393e08d/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L67) client which comes from the `UserContext` used at registration time
4. that `UserContext` in turn [comes from the Cluster Manager](https://github.com/rancher/rancher/blob/3c1c5730afc57546b362b2010744efdc7b77212b/pkg/clustermanager/manager.go#L223)'s internal record
5. that is [in turn configured by ToRESTConfig](https://github.com/rancher/rancher/blob/3c1c5730afc57546b362b2010744efdc7b77212b/pkg/clustermanager/manager.go#L414-L425) which, crucially, calls the Dialer factory's `ClusterDialer` func
6. `ClusterDialer` further delegates to `clusterFunc` which is where the code you pointed at decides if a tunnel is needed or not

Now no matter how `clusterFunc` decides, I expect to see an endpoint that returns namespaces (possibly 0) if the API works.

Are there reasons I am missing why the choice of whether using the tunnel or not could have effects?

Thanks in advance!

2024-02-06 19:59 UTC, Oats87 commented
> > @moio yoy may need to check to see if the cluster even needs a dialer, see:
> > https://github.com/rancher/rancher/blob/5314106f746c0c62e95d54922a2dfd116d2f6f68/pkg/dialer/factory.go#L189-L192
> > 
> > there are specific cluster types where we don't dial using the tunnel dialer
> 
> I did not know about that part of the code, I learned something, thanks for sharing.
> 
> Nevertheless I fail to see how the fact of using a tunnel dialer or not could impact the proposed change in this PR.
> 
> Please correct any errors in my reasoning:
> 
>     1. this patch relies on the `ClusterConditionReady` condition being correctly set
> 
>     2. the only place in the code where that is set is in [HealthSyncer](https://github.com/rancher/rancher/blob/e4e0fdd7991ef236d3d096e6473f42f26393e08d/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L150-L162), which periodically [attempts to look up a namespace](https://github.com/rancher/rancher/blob/e4e0fdd7991ef236d3d096e6473f42f26393e08d/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L89) as a means to check whether the cluster's API is ready
> 
>     3. that namespace look up [uses the `HealthSyncer.k8s`](https://github.com/rancher/rancher/blob/e4e0fdd7991ef236d3d096e6473f42f26393e08d/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L67) client which comes from the `UserContext` used at registration time
> 
>     4. that `UserContext` in turn [comes from the Cluster Manager](https://github.com/rancher/rancher/blob/3c1c5730afc57546b362b2010744efdc7b77212b/pkg/clustermanager/manager.go#L223)'s internal record
> 
>     5. that is [in turn configured by ToRESTConfig](https://github.com/rancher/rancher/blob/3c1c5730afc57546b362b2010744efdc7b77212b/pkg/clustermanager/manager.go#L414-L425) which, crucially, calls the Dialer factory's `ClusterDialer` func
> 
>     6. `ClusterDialer` further delegates to `clusterFunc` which is where the code you pointed at decides if a tunnel is needed or not
> 
> 
> Now no matter how `clusterFunc` decides, I expect to see an endpoint that returns namespaces (possibly 0) if the API works.
> 
> Are there reasons I am missing why the choice of whether using the tunnel or not could have effects?
> 
> Thanks in advance!

I may be outdated in my understanding here but the problem is that with older provisioning lifecycles of managed Kubernetes clusters, we relied on Rancher being able to dial the API server of the downstream cluster to initially deploy the `cattle-cluster-agent`. Implementing your proposed fix introduces a chicken-and-egg situation for that case where we are deploy the `cattle-cluster-agent` which runs the `healthsyncer` which means the `Ready` condition will never be set to `True` and we cannot use `cluster-deploy`. 

It's also important to note that we rely on `ClusterDeploy` to "fix" broken configurations of a cluster downstream as well, provided we have some method of dialing into it. This includes the use of the `cattle-node-agent` in RKE1 clusters, which is *not* considered a `cluster-agent` and will not run the controllers necessary.

Thinking about this further I am not necessarily comfortable with our reliance on the "house of cards" you have stated for management of the `cattle-cluster-agent`, rather, I would prefer we find a more robust method of determining whether we have an active dialer connection to the downstream cluster (if one is necessary) and use that to determine whether `clusterdeploy` operates or not.

2024-02-08 11:40 UTC, erkki commented
We are currently reverting this in our prod clusters as we see a regression as per https://github.com/rancher/rancher/issues/39597#issuecomment-1858728220 . Need to work on a safe testing environment -- in this case we only saw this regression when over 100 clusters were deployed (with 80% not connected).

2024-02-08 16:29 UTC, moio commented
> [...] Implementing your proposed fix [for managed clusters] introduces a chicken-and-egg situation for that case where we are deploy the `cattle-cluster-agent` which runs the `healthsyncer` which means the `Ready` condition will never be set to `True` and we cannot use `cluster-deploy`.

You are right, I could reproduce the problem trying to deploy an AKS cluster. I now understand the `ClusterDialer` factory that is ultimately used by `clusterdeploy` will return a non-tunneled connection to the Kubernetes cluster API which will work before `HealthSync` even starts. I could not see the problem before because all user cases I was studying (and my own setup) were using imported clusters, where this is not an issue.

I now understand and agree this is not the way to go.

> It's also important to note that we rely on `ClusterDeploy` to "fix" broken configurations of a cluster downstream as well, provided we have some method of dialing into it. This includes the use of the `cattle-node-agent` in RKE1 clusters, which is _not_ considered a `cluster-agent` and will not run the controllers necessary.

I now understand that `ClusterDialer` will attempt connecting in various ways, including connecting directly to any control plane node if direct connection is not an option and tunnel is not ready for whatever reason.

> Thinking about this further I am not necessarily comfortable with our reliance on the "house of cards" you have stated for management of the `cattle-cluster-agent`, rather, I would prefer we find a more robust method of determining whether we have an active dialer connection to the downstream cluster (if one is necessary) and use that to determine whether `clusterdeploy` operates or not.

I am working at a new patch that will use the existing mechanisms but the blocking part of connection opening.

I will ask you for another review when that passes my own testing at least.

Thanks for putting me on a better track!

2024-02-26 13:12 UTC, moio commented
@Oats87 can you take a look at the new version of this change which is radically different and (to my understanding) follows your comments?

Thanks in advance

2024-02-27 12:44 UTC, moio commented
@Oats87 related: what would be your opinion about extending this approach to `statsaggregator` (see 460eb9ac9) and potentially other controllers?

2024-03-08 18:58 UTC, Oats87 submitted a review, later dismissed
Silvio, this is great.

Thanks for breaking up the changes into "bite size chunks" across commits.

2024-03-08 19:02 UTC, jakefhyde approved these changes
Approving. Left some addressable feedback but honestly it's all minor stuff and pedantic.

2024-03-12 17:39 UTC, moio commented on pkg/clustermanager/manager.go
> +func ToRESTConfig(cluster *apimgmtv3.Cluster, context *config.ScaledContext, secretLister v1.SecretLister, tryReconnecting bool) (*rest.Config, error) {
I like that and will actually take it as a habit. Thanks!
Addressed as e2851cc31

2024-03-12 17:41 UTC, moio commented on pkg/clustermanager/manager.go
>  func (m *Manager) UserContextNoControllers(clusterName string) (*config.UserContext, error) {
Totally agreed both on the idea of a fluent API and the consideration this is best left for a follow-up refactoring PR once work on this is finalized.

I am resolving this conversation for now.

2024-03-12 17:52 UTC, moio commented on pkg/clustermanager/manager.go
> +func (m *Manager) UserContextNoControllersReconnecting(clusterName string, tryReconnecting bool) (*config.UserContext, error) {
I count 20 call sites that need to retain the current behavior, and 2 call sites where we want change it (perhaps they will grow a bit in the future).

The trade-off to strike is: verbosity here (in the form of the alias func) vs clarity in most of the calling locations (what does this extra `true` do?)

With this patch intent was to highlight the places where we are changing things, and leave alone places where we are not really changing anything. As you mentioned to lower review noise, also potentially make cherry-picking easier.

But the final word is really on maintnainers I believe, and I am totally fine reversing the decision. What would be your preference?

2024-03-12 17:54 UTC, moio commented on pkg/types/config/dialer/dialer.go
> +	ClusterDialer(clusterName string, retryOnError bool) (Dialer, error)
Agreed, this should go to a refactoring PR. Resolving this conversation for now

2024-03-12 18:33 UTC, moio commented on pkg/controllers/managementuser/healthsyncer/healthsyncer.go
> +	if _, err := k8s.CoreV1().Namespaces().Get(ctx, "kube-system", metav1.GetOptions{}); err != nil && !apierrors.IsNotFound(err) {
Easier is in the eye of the beholder I guess!

I tentatively pushed the approach you suggested (or at least what I hope I got correctly) as 666c2ff91.

I do not have any personal preference - on one hand using simple interfaces more and complicated mock mechanisms less is better, and I agree test code is now easier to follow. On the other hand, it does push a bit of extra complexity to `IsAPIUp` call sites, and those could grow a bit in count in the future, and test code is more verbose.

As you prefer. Please let me know if you actually like it better or I can also just remove it.

2024-03-12 18:35 UTC, moio commented
Thanks for the reviews! Minor details still up to discussion.

I will merge as soon as either @erkki or some other user can confirm this helps out there in the field.

2024-03-13 07:37 UTC, erkki commented
> Thanks for the reviews! Minor details still up to discussion.
> 
> I will merge as soon as either @erkki or some other user can confirm this helps out there in the field.

We in fact just deployed the pre-updated version in the field yesterday, will rebase on top of the latest changes and give it a few days of running in the wild.

2024-03-18 17:07 UTC, Oats87 approved these changes

2024-03-19 16:32 UTC, jakefhyde approved these changes

2024-03-23 09:40 UTC, erkki commented
> > Thanks for the reviews! Minor details still up to discussion.
> > I will merge as soon as either @erkki or some other user can confirm this helps out there in the field.
> 
> We in fact just deployed the pre-updated version in the field yesterday, will rebase on top of the latest changes and give it a few days of running in the wild.

We have now been running the patch-set with all of our existing patches reverted (including bumping of controller numbers) and things are looking sane and stable. It took us longer to isolate as we were running into some unrelated issues (for which we will send a new report) but this patch looks stable -- job times are sane and seemingly no queue blockages.

2024-03-26 08:06 UTC, merged