Remove monitoring v1
rancher/rancher pull request #43886
Opened 2023-12-29 19:54 UTC by diogoasouza

Monitoring v1 was deprecated on rancher 2.5, this PR removes the codebase.

https://github.com/rancher/rancher/issues/43325

2024-01-19 07:23 UTC, rohitsakala requested changes

2024-01-19 16:50 UTC, vardhaman22 approved these changes

2024-01-22 14:25 UTC, joshmeranda approved these changes
LGTM. I was never involved with the monitoring v1 development, so if we can get @aiyengar2 to sign off as well we'll be in good shape here.

2024-01-22 14:34 UTC, joshmeranda commented on pkg/monitoring/monitoring.go
I think we need some of this code to continue to expose some data from the rancher api to be consumed by users via UI

2024-01-23 05:41 UTC, aiyengar2 approved these changes

2024-01-23 05:45 UTC, aiyengar2 requested changes
missed one issue

2024-01-23 05:45 UTC, aiyengar2 commented on pkg/data/management/role_data.go
> -	rb.addRoleTemplate("View Monitoring", "monitoring-ui-view", "project", true, false, false)
This shouldn’t be removed as it is tied to Monitoring V2

2024-02-01 04:21 UTC, rohitsakala commented
Closing in favour of https://github.com/rancher/rancher/pull/44229

2024-02-01 04:21 UTC, closed without merging