[v2prov] Set machine join URL annotation on plan secret if not already set when loading plan
rancher/rancher pull request #44061
Opened 2024-01-17 00:40 UTC by Oats87

## Issue: 
https://github.com/rancher/rancher/issues/42856
 
## Problem
In certain cases, it is possible to encounter errors as the join URL annotation was added to a later version of Rancher. If the join URL was not already set on the plan secret, the planner may error out.

## Solution
Set the join URL on loading the plan.
 
## Testing

## Engineering Testing
### Manual Testing
Ran through the test case

### Automated Testing

* Test types added/modified:
    * Unit

## QA Testing Considerations

 
### Regressions Considerations
I attempted to cover regression potential with the unit test cases I added.

2024-05-20 19:49 UTC, snasovich commented
@Oats87 , is this still relevant? Reopening meanwhile.
@jakefhyde , could you please review?

2024-05-22 19:53 UTC, jakefhyde approved these changes

2024-05-23 21:37 UTC, jakefhyde requested changes

2024-05-23 21:37 UTC, jakefhyde commented on pkg/capr/planner/store_test.go
> +	"github.com/rancher/wrangler/pkg/generic"
```suggestion
	"github.com/rancher/wrangler/v2/pkg/generic"
```

2024-06-12 19:15 UTC, jakefhyde approved these changes

2024-07-29 17:14 UTC, Oats87 commented
Force-pushed a rebase onto `release/v2.9` for the purposes of re-running this PR through GHA

2024-09-03 17:40 UTC, merged