[Backport v2.7.11] Don't render providerID field into machine provision arguments
rancher/rancher pull request #44201
Opened 2024-01-23 21:12 UTC by Oats87

## Backport Issue:
https://github.com/rancher/rancher/issues/44198

## Original Issue: 
https://github.com/rancher/rancher/issues/43505

## Backport of:
https://github.com/rancher/rancher/issues/43511
https://github.com/rancher/rancher/pull/43512
 
## Problem
The `providerID` field is set on an infrastructuremachine object after the node corresponding to the machine has successfully registered. If this field is set before the infrastructuremachine object ready condition is set to `True`, it can cause a re-run of the machine provision job that will error due the unrecognized argument.

## Solution
Ignore the providerID field if it is set in the `InfrastructureMachine` spec.
 
## Testing

## Engineering Testing
### Manual Testing
I provisioned a vSphere cluster with this change.

### Automated Testing
* Test types added/modified:
    * None
* If "None" - Reason: The existing machineprovision tests in the e2e framework should cover regression validation of the change

Summary: N/A

## QA Testing Considerations

 
### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

2024-01-23 21:19 UTC, jakefhyde approved these changes

2024-01-23 23:36 UTC, thatmidwesterncoder approved these changes

2024-01-24 17:12 UTC, snasovich requested changes
Please fill out "QA Testing Considerations" section on PR template.

2024-01-29 15:42 UTC, snasovich approved these changes
LGTM, thank you for expanding PR description.

2024-02-01 23:20 UTC, merged