[2.9] Clean up orphaned ClusterUserAttribute
rancher/rancher pull request #44915
Opened 2024-03-25 16:05 UTC by pmatseykanets

Ref: https://github.com/rancher/rancher/issues/44914

## Issue: 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

## QA Testing Considerations

 
### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

2024-03-27 18:40 UTC, crobby submitted a review, later dismissed
lgtm

2024-03-27 18:59 UTC, MbolotSuse requested changes
A couple of comments, and one issue that I think is a bug.

2024-03-27 19:38 UTC, pmatseykanets commented on pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute.go
> +			userAttribute, err = h.userAttribute.Get("", metav1.GetOptions{})
Duh 🤦‍♂️ . Thanks for catching this!

2024-03-27 19:43 UTC, pmatseykanets commented on pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute.go
> +	if !clusterUserAttribute.NeedsRefresh {
We can leave it where it was L20 but then we'll be checking for missing user attribute  only when  `clusterUserAttribute.NeedsRefresh == true`.

2024-03-27 20:19 UTC, MbolotSuse commented on pkg/controllers/managementuser/clusterauthtoken/cluster_user_attribute.go
> +	if !clusterUserAttribute.NeedsRefresh {
Resolving, while this isn't strictly necessary leaving it behind the `NeedsRefresh` gate could also have some bad impacts.

2024-03-27 20:20 UTC, MbolotSuse approved these changes

2024-03-27 20:20 UTC, MbolotSuse commented
@pmatseykanets LGTM, but please squash the commits when merging.

2024-03-27 20:23 UTC, pmatseykanets commented
> but please squash the commits when merging.
Always

2024-03-27 20:27 UTC, JonCrowther submitted a review, later dismissed

2024-03-28 16:45 UTC, crobby approved these changes

2024-03-28 17:41 UTC, merged