[v2.7] Bump docker-machine-driver-linode to v0.1.12
rancher/rancher pull request #45223
Opened 2024-04-24 17:29 UTC by ykim-1

## Issue: https://github.com/linode/docker-machine-driver-linode/issues/131
 
## Problem
bump docker-machine-driver-linode version to latest v0.1.12
 
## Solution
update dependancy to latest so that it reflects CVEs that are already fixed

2024-04-24 18:40 UTC, pjbgf commented
Thanks for raising this PR @ykim-1! :bow: 

Approving as per SURE-7072 and based on the [release changes](https://github.com/linode/docker-machine-driver-linode/releases/tag/v0.1.12).

2024-07-02 10:58 UTC, macedogm commented
Can the following lines also be bumped to the same version, please?
- https://github.com/rancher/rancher/blob/release/v2.7/tests/v2/codecoverage/package/Dockerfile#L38
- https://github.com/rancher/rancher/blob/release/v2.7/pkg/data/management/machinedriver_data.go#L113

I honestly don't know if something else should be bumped too or not. Pinging Hostbusters and @snasovich for review this also.

2024-07-30 11:26 UTC, pjbgf approved these changes

2024-07-31 01:44 UTC, snasovich requested changes
Same as https://github.com/rancher/rancher/pull/45220#pullrequestreview-2208987636

Edit: However, I'm not sure there will be another 2.7.x release at this time

2024-07-31 23:16 UTC, snasovich approved these changes

2024-08-01 02:11 UTC, macedogm approved these changes

2024-09-25 19:38 UTC, merged