Data dir rfc
rancher/rancher pull request #45326
Opened 2024-05-01 20:20 UTC by jakefhyde

## Issue: 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

## QA Testing Considerations

 
### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

2024-06-04 18:18 UTC, jakefhyde commented on pkg/rancher/migrations.go
> +		for i, e := range cluster.Spec.AgentEnvVars {
I think I need to redo this migration for bounds checking.

2024-06-25 19:12 UTC, Oats87 approved these changes

2024-06-25 23:13 UTC, jiaqiluo requested changes

2024-06-25 23:13 UTC, jiaqiluo commented on tests/v2prov/cluster/clusters.go
> +		}
nit: to make it easier to understand, same to the following two ifs. 
```suggestion
		if cluster.Spec.RKEConfig.DataDirectories.K8sDistro == "" {
			cluster.Spec.RKEConfig.DataDirectories.K8sDistro = defaults.DistroDataDir
		}
```

2024-06-25 23:14 UTC, jiaqiluo commented on pkg/capr/planner/idempotent.go
>  shift 4
This has been fixed in the following commits.

2024-06-25 23:22 UTC, jiaqiluo commented on pkg/rancher/migrations.go
> +			if e.Name == "CATTLE_AGENT_VAR_DIR" {
nit: use the global variable in pkg/capr/installer/installer.go,  instead of hard-coded value.

2024-06-26 15:51 UTC, jakefhyde commented on pkg/controllers/capr/bootstrap/controller.go
> +	systemAgentVarDirEnvVar                = "CATTLE_AGENT_VAR_DIR"
It's defined in the system agent installer script, so it cannot be redefined.

2024-06-26 19:42 UTC, jiaqiluo approved these changes

2024-06-27 16:12 UTC, Oats87 approved these changes

2024-06-27 18:21 UTC, brandond requested changes
nit on relying on the k3s kubectl symlink

2024-06-27 18:21 UTC, brandond commented on pkg/capr/common.go
>  		return K3sKubectlPath, K3sKubeconfigPath
is it safe to rely on k3s always linking its installed kubectl as `/usr/local/bin/kubectl`? I'm not sure this is future-proof, as we move onto distros that use transactional updates and/or immutable filesystems that will cause changes to /usr/local/bin to be lost on restart.

I think we should instead switch to using something like:
```golang
var (
  K3sRelativeKubectlPath = "data/current/bin/kubectl"
)
// ...
return path.Join(GetDistroDataDir(controlPlane), K3sRelativeKubectlPath`, K3sKubeconfigPath
```

2024-06-27 23:43 UTC, merged