Implemented time out report to log cluster status and condition infor…
rancher/rancher pull request #46042
Opened 2024-07-06 20:04 UTC by lscalabrini01

- Changed provisioning tests to use TimeoutRKEReport and TimeoutClusterReport

2024-07-11 17:18 UTC, floatingman requested changes
Looks good. Do you have test runs in Jenkins? If so, can you post it in the test-automation channel?

2024-07-11 17:18 UTC, floatingman commented on go.mod
> +	github.com/rancher/shepherd => github.com/lscalabrini01/shepherd v0.0.0-20240705200636-a86b49c33452
Be sure to change this before merging

2024-07-11 17:57 UTC, lscalabrini01 commented on go.mod
> +	github.com/rancher/shepherd => github.com/lscalabrini01/shepherd v0.0.0-20240705200636-a86b49c33452
Yes, for sure

2024-07-16 03:12 UTC, floatingman approved these changes
LGTM

2024-07-22 14:46 UTC, closed without merging