Harvester arm driver
rancher/rancher pull request #46089
Opened 2024-07-09 23:19 UTC by ibrokethecloud

## Issue: 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

## QA Testing Considerations

 
### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

2024-07-17 15:05 UTC, innobead submitted a review, later dismissed
In general, LGTM.

However, the current implementation of MachineDriver mgmt seems not consider multi-arch design, so the PR here is more just fix specially for Harvester. Not sure how other drivers will be handled in the future, as notice several are hard-coded with amd64 artifact. 

P.S. For checksums, it's better to publish them to the release page of the Harvester node driver as well, even though this is out of scope here.

2024-07-17 16:30 UTC, innobead commented
cc @khushboo-rancher

2024-07-18 17:06 UTC, jakefhyde requested changes
Minor nit, otherwise LGTM. As others have said, this is probably fine for harvester in the meantime, extending this to other drivers will likely require something more involved (feature enhancement or something).

2024-07-18 17:06 UTC, jakefhyde commented on pkg/data/management/machinedriver_data.go
> +	goruntime "runtime"
```suggestion
	"runtime"
```
Nit: runtime is self-explanatory IMO

2024-07-19 01:48 UTC, ibrokethecloud commented
may be we should move to inject driver file checksums as build variables, this can then be done in docker build based on arch being built and file being downloaded

2024-08-08 19:51 UTC, jakefhyde submitted a review, later dismissed

2024-08-09 03:07 UTC, bk201 approved these changes

2024-09-11 23:44 UTC, Oats87 requested changes

2024-09-11 23:44 UTC, Oats87 commented on pkg/data/management/machinedriver_data.go
> +
unnecessary newline

2024-09-19 10:04 UTC, m-ildefons commented
Just my two cents:

There has been [this PR](https://github.com/harvester/docker-machine-driver-harvester/pull/61) since the last release, which provides a fix that is quite critical to get [this workaround](https://harvesterhci.io/kb/renew_harvester_cloud_credentials/) to work right.
We should do another release of the Harvester node driver, which includes the fix. That would mean, that we would need to update this PR to include that.

It may be out of scope for now, but I think it would be worthwhile to consider [injecting the version and checksums as build time variables](https://blog.alexellis.io/inject-build-time-vars-golang/) instead of hard-coding them in the Golang code.
Then the Dockerfile would serve as the single source of truth and updates would become much easier, since no changes to the Golang code would be necessary.

2024-09-25 19:19 UTC, Oats87 approved these changes

2024-09-25 21:41 UTC, jakefhyde approved these changes

2024-09-25 22:39 UTC, merged