Migrating serviceaccounts test from python to go
rancher/rancher pull request #46682
Opened 2024-08-13 18:48 UTC by joesims22

## Issue: 
[rancher/qa-tasks#1343](https://github.com/rancher/qa-tasks/issues/1343)
Note: Backports will be created once this gets approved

2024-09-05 20:09 UTC, brudnak approved these changes
lgtm!

2024-09-09 18:42 UTC, Priyashetty17 requested changes
Have a few minor comments

2024-09-09 18:42 UTC, Priyashetty17 commented on tests/v2/validation/serviceaccounts/README.md
> +  cleanup: false/optional
nit, can you change this to : 
`cleanup: true/optional`

2024-09-09 18:42 UTC, Priyashetty17 commented on tests/v2/validation/serviceaccounts/sa_test.go
> +	"github.com/rancher/shepherd/extensions/serviceaccounts"
Looks like this extension is no longer available and has been moved to actions here: https://github.com/rancher/rancher/blob/main/tests/v2/actions/serviceaccounts/serviceaccounts.go 

Can you change this to: 
"github.com/rancher/rancher/tests/v2/actions/serviceaccounts"

2024-09-12 16:46 UTC, Priyashetty17 approved these changes
lgtm

2024-09-12 18:11 UTC, merged