Remove internal endpoint for object counts in downstream clusters
rancher/rancher pull request #46861
Opened 2024-08-28 10:44 UTC by aruiz14

## Issue: #46860

 
## Problem
This API endpoint is internal and not documented. Instead of fixing it (see issue description), let's just drop it.
 
## Solution
Remove `/metrics/{clusterID}` handling, while keeping Prometheus' `/metrics` endpoint (and SubjectAccess validation) available.
 
## Testing

## Engineering Testing
### Manual Testing
 - Accessing `/metrics/local` shows not found ✅ .
 - Accessing `/metrics` logged in as `admin` shows Prometheus metrics ✅ 
 - Accessing `/metrics` logged in as non-admin user with `View Rancher Metrics` permissions granted shows Prometheus metrics ✅ 
 - Accessing `/metrics` logged in as non-admin user with no additional permissions granted shows `401 Unauthorized` ✅ 

### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

## QA Testing Considerations

 
### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

2024-08-28 11:50 UTC, bigkevmcd requested changes

2024-08-28 11:50 UTC, bigkevmcd commented on pkg/metrics/handler.go
> +type metricsHandler struct {
How about a comment that says...

```go
metricsHandler is an HTTP middleware that verifies that the user making the request can get  ranchermetrics resources before calling the provided handler.

This uses the Impersonate-User and Impersonate-Groups HTTP headers to check access.
```

Also, there's nothing specific to prometheus here, so maybe we drop the references to Prometheus and `prom` in the parameters and struct field?

2024-08-28 11:50 UTC, bigkevmcd commented on pkg/metrics/handler.go
> +		util.ReturnHTTPError(rw, req, 401, "Unauthorized")
```suggestion
		util.ReturnHTTPError(rw, req, http.StatusUnauthorized, "Unauthorized")
```

2024-08-28 11:50 UTC, bigkevmcd commented on pkg/metrics/handler.go
> +		promHandler:               promHandler,
If this was me, I'd pass in a `v1.SubjectAccessReviewInterface` rather than the `kubernetes.Interface` ?

2024-08-28 11:50 UTC, bigkevmcd commented on pkg/metrics/handler.go
> +		util.ReturnHTTPError(rw, req, 500, err.Error())
```suggestion
		util.ReturnHTTPError(rw, req, http.StatusInternalServerError, err.Error())
```

2024-08-28 13:14 UTC, moio submitted a review, later dismissed

2024-08-29 08:18 UTC, moio approved these changes

2024-08-29 12:12 UTC, bigkevmcd approved these changes

2024-09-04 07:02 UTC, merged