[release-v2.7] GH Actions migration [small-fixes]
rancher/rancher pull request #46961
Opened 2024-09-04 21:36 UTC by nicholasSUSE

Migrating release/v2.7 to use Github Actions most up-to-date jobs.

2024-09-04 21:37 UTC, briandowns approved these changes

2024-09-05 14:43 UTC, tashima42 requested changes

2024-09-05 14:43 UTC, tashima42 commented on .github/workflows/push-release.yml
> +          echo "CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION" >> "$GITHUB_ENV"
This isn't valid for `release/v2.7`, instead, the webhook version is manually set on the `Dockerfile.agent`

2024-09-05 15:40 UTC, tashima42 approved these changes

2024-09-05 18:58 UTC, merged