[v2.8] Fix go-get CI and script
rancher/rancher pull request #47052
Opened 2024-09-11 09:44 UTC by chiukapoor

## Updates
- Add `go generate` step to `go-get` script
- Fix token for PR generation for CI invocation

## Issue:
- https://github.com/rancher/rancher/issues/47014

2024-09-11 18:07 UTC, tashima42 submitted a review, later dismissed

2024-09-12 04:41 UTC, kinarashah submitted a review, later dismissed

2024-10-01 01:51 UTC, tashima42 approved these changes

2024-10-01 03:03 UTC, tashima42 requested changes
App not working: https://github.com/rancher/rancher/actions/runs/11117709941/job/30890088813#step:13:132

2024-10-01 09:49 UTC, tashima42 approved these changes
It was an issue with that run: https://github.com/rancher/rancher/actions/runs/11117709941/job/30894173775

2024-10-04 04:42 UTC, kinarashah approved these changes

2024-10-04 08:52 UTC, merged