Replace loglevel binary with small shell script
rancher/rancher pull request #47194
Opened 2024-09-19 17:30 UTC by brandond

## Issue: SURE-8512
 
## Problem
The loglevel binary is built from a separate project that is essentially unmaintained: https://github.com/rancher/loglevel/blob/master/main.go

It serves very little purpose and is just a thin wrapper around a HTTP API presented via unix socket within the rancher container.
 
## Solution
Replace project and binary with shell script. Shell script should support the same CLI flags and env vars as the binary.
 
## Testing

Covered by tests

## Engineering Testing

### Manual Testing

Ran the script myself, seems to work

### Automated Testing
* Test types added/modified:
    * Integration (Go Framework)

## QA Testing Considerations
 
### Regressions Considerations

Existing / newly added automated tests that provide evidence there are no regressions:

2024-09-19 17:46 UTC, macedogm approved these changes

2024-09-20 14:45 UTC, MbolotSuse requested changes
One request for help options.

2024-09-20 14:59 UTC, HarrisonWAffel approved these changes
LGTM, thanks for removing the comment in `windows/Dockerfile.agent`. I'm not aware of any place where Windows actually uses the `loglevel` binary.

2024-09-23 11:57 UTC, macedogm submitted a review, later dismissed

2024-09-24 19:01 UTC, brandond commented on package/loglevel
> +    --help|-h )
sure why not

2024-09-24 19:17 UTC, MbolotSuse approved these changes

2024-09-24 19:28 UTC, macedogm approved these changes

2024-09-25 16:34 UTC, brandond commented
Should I merge this myself now that it's approved, or should someone on the Rancher side do it? Same question re: backports.

2024-09-25 16:43 UTC, MbolotSuse commented
@brandond Totally up to you. Typically I like to let the PR author merge (in case they find something that they would like to change last minute), but if you don't have the permissions I can do it.

Similar answer for the backports, typically the PR author would do it but I can if you would like.

2024-09-25 16:57 UTC, merged

2024-09-25 16:58 UTC, brandond commented
What branch should I target with the backport? release/v2.9?