<v2.9> Converted test_wl_pause_orchestration from python to go
rancher/rancher pull request #47344
Opened 2024-10-01 22:12 UTC by lscalabrini01

2024-10-03 13:35 UTC, floatingman submitted a review, later dismissed
LGTM

2024-10-03 18:21 UTC, slickwarren requested changes
I don't think this has been rebased from your latest changes on main, right?

2024-10-03 18:21 UTC, slickwarren commented on tests/v2/actions/workloads/deployment/deployment.go
updateDeployment wasn't ported here, should it be?

2024-10-03 18:30 UTC, lscalabrini01 commented
> I don't think this has been rebased from your latest changes on main, right?

2024-10-03 18:33 UTC, lscalabrini01 commented on tests/v2/actions/workloads/deployment/deployment.go
Yes, it hasn't been rebased from my latest changes on main. I'm waiting for the main changes to be merged before updating the backports

2024-10-04 18:01 UTC, slickwarren approved these changes

2024-10-04 20:14 UTC, floatingman submitted a review, later dismissed
LGTM

2024-10-04 23:45 UTC, slickwarren approved these changes

2024-10-07 19:42 UTC, anupama2501 approved these changes

2024-10-07 19:44 UTC, merged