update cluster agent manifest
rancher/rancher pull request #47620
Opened 2024-10-18 20:30 UTC by kinarashah

2024-10-24 00:32 UTC, jiaqiluo requested changes

2024-10-24 00:32 UTC, jiaqiluo commented on pkg/capr/configserver/agent.go
> +	tokens, err := r.clusterTokenCache.GetByIndex(tokenIndex, token)
Can we rename the variable to minimize confusion?
```suggestion
	clusterTokens, err := r.clusterTokenCache.GetByIndex(tokenIndex, token)
```

2024-10-24 00:32 UTC, jiaqiluo commented on pkg/capr/configserver/agent.go
> +		mgmtCluster, systemtemplate.GetDesiredFeatures(mgmtCluster), taints, r.secretsCache)
We can refactor the code by calling an existing function to simplify it.
```suggestion
	clusterAgentTemplate, err := systemtemplate.ForCluster(mgmtCluster, token, taints, r.secretsCache)
```

2024-10-24 00:32 UTC, jiaqiluo commented on pkg/capr/configserver/agent.go
> +	}
I noticed that in another function we [sort the tokens slice](https://github.com/rancher/rancher/blob/main/pkg/capr/planner/agent.go#L26-L28) and start using the [`tokens[0]`'s values afterward](https://github.com/rancher/rancher/blob/main/pkg/capr/planner/agent.go#L40), 
should we also do it here?

2024-10-24 00:32 UTC, jiaqiluo commented on pkg/capr/planner/manifests.go
> +func (p *Planner) getClusterAgentManifestFile(controlPlane *rkev1.RKEControlPlane, runtime string, entry *planEntry) (plan.File, error) {
Both `runtime` and `entry` are unused parameters, can we remove them?

2024-10-24 00:32 UTC, jiaqiluo commented on pkg/capr/planner/agent.go
> +	exit 1
Can we print some error messages to make it easier for troubleshooting when it is necessary?

2024-12-06 20:23 UTC, jakefhyde requested changes

2025-02-10 16:53 UTC, kinarashah commented
Relevant, need to address PR comments - hopefully next week

2025-03-05 12:03 UTC, kinarashah commented on pkg/capr/planner/agent.go
> +	info "cattle-cluster-agent already exists"
I think this will be fine as the manifest on disk now only refers to the job, not actual manifest: https://github.com/rancher/rancher/blob/a0de3ebc35b932795e74df0b714cccf4eeced782/pkg/capr/planner/agent.go#L61 

Actual manifest is removed after applying, 
https://github.com/rancher/rancher/blob/a0de3ebc35b932795e74df0b714cccf4eeced782/pkg/capr/planner/agent.go#L366

2025-03-07 18:07 UTC, jakefhyde submitted a review, later dismissed

2025-03-07 21:31 UTC, HarrisonWAffel submitted a review, later dismissed

2025-03-07 23:42 UTC, jiaqiluo requested changes
I have a few questions but overall LGTM.

2025-03-07 23:42 UTC, jiaqiluo commented on pkg/capr/configserver/server.go
> +	}
Should it return here to really short-circuit? 
```suggestion
  return 
	}
```

2025-03-07 23:42 UTC, jiaqiluo commented on pkg/capr/planner/agent.go
> +		}
Is it possible that the `ev.Value` is "false"? Does it matter?

2025-03-07 23:42 UTC, jiaqiluo commented on pkg/capr/configserver/server.go
> +	ConnectClusterAgentYamlPath = "/v3/connect/cluster-agent/{token}.yaml"
Could you explain a bit about how the new endpoint will be used?

2025-03-10 08:57 UTC, kinarashah commented on pkg/capr/configserver/server.go
> +	ConnectClusterAgentYamlPath = "/v3/connect/cluster-agent/{token}.yaml"
`connectClusterAgentYAML` returns a cattle-cluster-agent manifest for the given bearer token, this path is called by the agent manifest script sent via planner https://github.com/rancher/rancher/pull/47620/files#diff-955ac5704543565a62e69b77145857cdbbde42acdb4b154c879e899097302426R348

2025-03-10 15:59 UTC, jiaqiluo submitted a review, later dismissed
LGTM

2025-04-10 16:53 UTC, kinarashah commented
Ready to merge now that we have `release/v2.11` branch.

2025-04-14 21:17 UTC, jiaqiluo approved these changes

2025-04-14 23:20 UTC, merged