[main] Fix `provisioning-tests` to use rancher-agent image built from current branch
rancher/rancher pull request #47699
Opened 2024-10-24 19:09 UTC by thatmidwesterncoder

## Issue: https://github.com/rancher/rancher/issues/47563 

 
## Problem

The `provisioning-tests` scripts would fall back to the default `CATTLE_AGENT_IMAGE` set in code when running - this would result in the tests failing any time any agent changes were made with rancher changes that depended on them. Most notably when adding features - if the feature flag was added to the agent env var list the agent would panic out due to not knowing how to handle the feature flag. 
 
## Solution

1. Load up the `rancher/rancher-agent` image built from a prior step into the docker daemon
2. Push that image to the `registry-cache` which is configured as a pull-through cache for the provisioning-tests
3. ???
4. Tests go green when agent changes are made!
 
## Testing

If the tests are green -> this change worked. 

## Engineering Testing
### Manual Testing

### Automated Testing

* Test types added/modified:
    * Provisioning-tests
  

Summary: Only changes made to the provisioning-tests was to add a `hostPort` to the registry-cache container so we can push to it from the docker daemon.

## QA Testing Considerations

N/A
 
### Regressions Considerations

None - no code changes outside of tests. 

Existing / newly added automated tests that provide evidence there are no regressions:
n/a

2025-01-16 22:44 UTC, jiaqiluo requested changes

2025-01-16 22:44 UTC, jiaqiluo commented on .github/workflows/provisioning-tests.yml
> -      - 'tests/validation/**'
Should this be added back to allow the provisioning tests to be triggered on PR?

2025-01-16 22:44 UTC, jiaqiluo commented on .github/workflows/provisioning-tests.yml
> +  GIT_TAG: v2.11-${{ github.sha }}-head
Is it possible to keep one of them since they have the same value?

2025-01-16 22:44 UTC, jiaqiluo commented on scripts/provisioning-tests
> +export CATTLE_AGENT_IMAGE=${CATTLE_AGENT_IMAGE:-rancher/rancher-agent:${AGENT_TAG}}
where is the env var `AGENT_TAG` defined?

2025-01-17 17:44 UTC, jiaqiluo approved these changes
LGTM

2025-01-17 18:58 UTC, jakefhyde requested changes

2025-01-17 18:58 UTC, jakefhyde commented on scripts/provisioning-tests
> +( push_cattle_agent_image & )
If you want https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.10/scripts/fetch-provisioning-tests to still work, I would recommend gating this with an environment variable like `PUSH_AGENT_IMAGE`, otherwise the KDM provisioning tests will break.

2025-01-22 11:44 UTC, jakefhyde approved these changes
Approving so you aren't blocked

2025-01-22 16:23 UTC, jiaqiluo approved these changes
lgtm

2025-01-22 21:39 UTC, merged