[release/v2.9] Enable provisioning-tests and integration-tests to use cgroupsv2
rancher/rancher pull request #47880
Opened 2024-11-04 21:37 UTC by Oats87

## Issue:
https://github.com/rancher/rancher/issues/46456

## Original Issue: 
https://github.com/rancher/rancher/issues/46222

## Summary:
This PR bumps `rancher/systemd-node` to `v0.0.5`, which contains a script that facilitates the usage of cgroupsv2.

It makes corrections to the logic used to run the integration-tests environment, as well as adding cgroups draining logic to the `provisioning-tests` script and corresponding Rancher `run`.

2024-11-04 22:10 UTC, jakefhyde approved these changes

2024-11-05 20:02 UTC, jakefhyde submitted a review, later dismissed

2024-11-13 17:40 UTC, snasovich requested changes
Have one comment on CPU increase to sort out.

2024-11-13 17:40 UTC, snasovich commented on .github/workflows/integration-tests.yml
> +      - runner=32cpu-linux-x64
That's quite a jump from 8 cores to 32. FWIW https://github.com/rancher/rancher/pull/47789 bumped it from 8 to 16 so this one is asking twice that.

I we're also changing from `spot=price-capacity-optimized` to `spot=capacity-optimized` so there is extra run cost here.

Is there an increased CPU requirement associated with cgroupsv2 enabled or marked speed up of tests execution?

Maybe we should consider 8 CPU cores + `spot=false` instead as potentially the same cost and better stability?

2024-11-19 23:08 UTC, snasovich approved these changes
Test approval, will be cleared

2024-11-20 00:09 UTC, snasovich requested changes
Restoring "Request changes"

2025-02-03 01:59 UTC, closed without merging