[main] Add spot=false to provisioning-tests and integration tests
rancher/rancher pull request #47892
Opened 2024-11-05 19:36 UTC by Oats87

## Issue: 
https://github.com/rancher/rancher/issues/46456
 
## Problem
GHA Runners keep stating "operation has been cancelled", and this is likely due to the usage of spot instances.

## Solution
Stop using spot instances.

2024-11-05 23:45 UTC, snasovich requested changes
Let's consider `spot=capacity-optimized` as the first step and see how well it performs - it may be a good middle-ground between tuning off spot instances completely and the default behavior.

2024-11-06 19:12 UTC, jakefhyde submitted a review, later dismissed

2024-11-06 19:48 UTC, jakefhyde commented
@snasovich Just an FYI, it looks like the first run after merging this resulted in this:
```
Error: The operation was canceled.
```

2024-11-06 21:17 UTC, snasovich commented
> @snasovich Just an FYI, it looks like the first run after updating this resulted in this:
> 
> ```
> Error: The operation was canceled.
> ```

@jakefhyde , yeah - saw that. It was worth a shot but seems like it's doesn't dramatically reduce the chance of running into the issue. I'm working with EIO to better understand the financial impact of turning off spot instances usage here before we proceed with stopping their usage (but yeah, `capacity-optimized` doesn't seem to be worth considering).

2025-01-26 02:00 UTC, closed without merging