updated logic for creating cattle-system namespace
rancher/rancher pull request #48427
Opened 2024-12-13 16:42 UTC by vardhaman22

## Issue: 

 https://github.com/rancher/rancher/issues/48419
## Problem

Etcd snapshot restore fails in PostCheck step when GenerateServiceAccountToken is called in some cases. If rke1 cluster k8s upgrade is done with Drain nodes enabled in upgrade strategy and then if we try to restore it to old k8s version using etcd snapshot the restore continuously fails in PostCheck with following error
`
err: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces.create-non-kubesystem": failed to call webhook: Post "[https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s](https://rancher-webhook.cattle-system.svc/v1/webhook/validation/namespaces?timeout=10s)": dial tcp 10.43.113.34:443: i/o timeout,
`

it happens when Create request is made for the cattle-system namespace. 
Since we are restoring the cluster, It already has a ValidatingWebhookConfiguration  ` rancher.cattle.io` which has a rule to validate namespace creation.
When the APIServer tries to connect to webhook this error occurs. 
the apiserver request to webhook can fail , since rancher webhook pod runs on  worker nodes which are upgraded only after this PostCheck pass.

So if only a GET request is sent then apiserver can respond directly and this webhook error will not occur.

## Solution

 
Instead of directly doing a create request for the cattle-namespace, first we a GET request is done to verify if the namespace already exist.

## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

* Test types added/modified:
    * Unit
    * Integration (Go Framework)
    * Integration (v2prov Framework)
    * Validation (Go Framework)
    * Other - Explain: _EXPLAIN_
    * None
    * _REMOVE NOT APPLICABLE BULLET POINTS ABOVE_
* If "None" - Reason: _EXPLAIN THE REASON_
  
* If "None" - GH Issue/PR: _LINK TO GH ISSUE/PR TO ADD TESTS_

Summary: _TODO_

## QA Testing Considerations

 
### Regressions Considerations

_TODO_

Existing / newly added automated tests that provide evidence there are no regressions:
* _TODO_

2025-01-07 18:10 UTC, jakefhyde requested changes

2025-01-07 18:10 UTC, jakefhyde commented on pkg/kontainer-engine/drivers/util/utils.go
> +		}
```suggestion
	_, err := clientset.CoreV1().Namespaces().Get(context.TODO(), cattleNamespace, metav1.GetOptions{})
	if err != nil {
		if !errors.IsNotFound(err) {
			return err
		}
		_, err = clientset.CoreV1().Namespaces().Create(context.TODO(), &v1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name: cattleNamespace,
			},
		}, metav1.CreateOptions{})
		// checking for already exist error to handle case of a timeout error of the get request
		if err != nil && !errors.IsAlreadyExists(err) {
			return "", fmt.Errorf("error creating namespace: %v", err)
		}
```
Although the webhook running may affect the create call, we should be able to tell if it doesn't exist with GET, unless there is some other situation where it may return an error other than `IsNotFound` but a create would succeed that I'm not aware about in this case.

2025-01-08 12:23 UTC, vardhaman22 commented on pkg/kontainer-engine/drivers/util/utils.go
> +		}
done..updated the code..added the NotFound error check and also removed the already exist error check while namespace creation

2025-01-08 17:30 UTC, jakefhyde approved these changes

2025-01-09 17:09 UTC, kinarashah approved these changes

2025-01-09 17:10 UTC, merged