DNM [2.8] Fixes the local upgrade failure
rancher/rancher pull request #48462
Opened 2024-12-17 19:56 UTC by anupama2501

Back port of 
https://github.com/rancher/rancher/pull/48292

### NOTE:
shepeherd changes are yet to be merged for this release. once that is merged, would need to update the go.mod changes in this PR.

2024-12-17 21:40 UTC, markusewalker submitted a review, later dismissed

2024-12-18 17:38 UTC, lscalabrini01 requested changes
The changes in this PR are not the same as those in the other PRs

2024-12-20 14:57 UTC, anupama2501 commented
@lscalabrini01 
The changes are due to updates in go.mod and go.sum. Please refer to the note in the PR for additional context under `Note`: [Rancher PR #48462](https://github.com/rancher/rancher/pull/48462#issue-2745912228).

2024-12-23 19:32 UTC, lscalabrini01 approved these changes

2024-12-23 19:36 UTC, rancher-max approved these changes

2024-12-23 20:47 UTC, merged